/**
 * Atoms Documentation
 * Complete documentation for all atom-level components
 */

import type { ComponentDoc } from '../types.js';

export const atoms: ComponentDoc[] = [
  // =============================================================================
  // Button Components
  // =============================================================================
  {
    name: 'Button',
    category: 'atoms',
    description: 'Interactive button with multiple variants, sizes, loading states, and icon support.',
    props: [
      { name: 'label', type: "string", required: true, description: 'Button label text' },
      { name: 'onClick', type: "() => void", required: false, description: 'Click handler' },
      { name: 'variant', type: "'solid' | 'outline' | 'ghost' | 'link'", required: false, default: "'solid'", description: 'Visual variant' },
      { name: 'size', type: "'small' | 'medium' | 'large'", required: false, default: "'medium'", description: 'Button size' },
      { name: 'color', type: "ColorValue", required: false, description: 'Button color (uses theme accent by default)' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'loading', type: "boolean", required: false, default: 'false', description: 'Show loading spinner' },
      { name: 'loadingText', type: "string", required: false, description: 'Text to show while loading' },
      { name: 'icon', type: "string", required: false, description: 'Icon before label (emoji or character)' },
      { name: 'iconRight', type: "string", required: false, description: 'Icon after label' },
      { name: 'fullWidth', type: "boolean", required: false, default: 'false', description: 'Expand to fill container' },
      { name: 'focused', type: "boolean", required: false, default: 'false', description: 'Focus state (for keyboard nav)' },
      { name: 'hovered', type: "boolean", required: false, default: 'false', description: 'Hover state (from mouse)' },
    ],
    examples: [
      `Button({ label: 'Submit', onClick: () => console.log('clicked') })`,
      `// With icon and variant\nButton({\n  label: 'Save',\n  icon: '💾',\n  variant: 'solid',\n  color: 'success',\n  onClick: handleSave,\n})`,
      `// Loading state\nButton({\n  label: 'Submit',\n  loading: isSubmitting(),\n  loadingText: 'Submitting...',\n  onClick: handleSubmit,\n})`,
      `// Ghost button\nButton({ label: 'Cancel', variant: 'ghost' })`,
    ],
    relatedComponents: ['IconButton', 'ButtonGroup'],
  },
  {
    name: 'IconButton',
    category: 'atoms',
    description: 'Button with just an icon, no label. Ideal for toolbars and compact UI.',
    props: [
      { name: 'icon', type: "string", required: true, description: 'Icon to display (emoji or character)' },
      { name: 'label', type: "string", required: true, description: 'Accessibility label (not displayed)' },
      { name: 'onClick', type: "() => void", required: false, description: 'Click handler' },
      { name: 'color', type: "ColorValue", required: false, description: 'Icon color' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'focused', type: "boolean", required: false, default: 'false', description: 'Focus state' },
      { name: 'hovered', type: "boolean", required: false, default: 'false', description: 'Hover state' },
    ],
    examples: [
      `IconButton({ icon: '🗑️', label: 'Delete', onClick: handleDelete })`,
      `// Toolbar icons\nBox({ flexDirection: 'row', gap: 1 },\n  IconButton({ icon: '📁', label: 'Open' }),\n  IconButton({ icon: '💾', label: 'Save' }),\n  IconButton({ icon: '↩️', label: 'Undo' }),\n)`,
    ],
    relatedComponents: ['Button', 'ButtonGroup'],
  },
  {
    name: 'ButtonGroup',
    category: 'atoms',
    description: 'Group of buttons with **built-in keyboard navigation** - no useInput needed! **API Pattern: Data-Driven** - buttons are defined in a buttons array, NOT as children.',
    props: [
      { name: 'buttons', type: "ButtonProps[]", required: true, description: 'Array of { label, onClick, variant?, color?, disabled? }' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'horizontal'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, default: '1', description: 'Gap between buttons' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard navigation' },
      { name: 'wrap', type: "boolean", required: false, default: 'true', description: 'Wrap around at edges' },
      { name: 'onFocusChange', type: "(index: number) => void", required: false, description: 'Called when focus changes' },
    ],
    examples: [
      `// ✅ Out-of-the-box keyboard navigation\nButtonGroup({\n  buttons: [\n    { label: 'Save', onClick: save, variant: 'solid', color: 'success' },\n    { label: 'Cancel', onClick: cancel, variant: 'outline' },\n  ],\n})\n// Arrow keys navigate, Enter/Space triggers onClick!`,
      `// Keyboard: ← → (or ↑ ↓ for vertical), Enter/Space to click, h/j/k/l vim keys`,
    ],
    relatedComponents: ['Button', 'IconButton'],
  },

  // =============================================================================
  // Input Components
  // =============================================================================
  {
    name: 'TextInput',
    category: 'atoms',
    description: 'Single or multi-line text input with cursor, history, password support, auto-grow, scrollbar, click-to-caret, and up/down navigation.',
    props: [
      { name: 'value', type: "string", required: false, description: 'Current value (for controlled mode)' },
      { name: 'initialValue', type: "string", required: false, default: "''", description: 'Initial value' },
      { name: 'onChange', type: "(value: string) => void", required: false, description: 'Change handler' },
      { name: 'onSubmit', type: "(value: string) => void", required: false, description: 'Enter key handler' },
      { name: 'placeholder', type: "string", required: false, description: 'Placeholder text when empty' },
      { name: 'password', type: "boolean", required: false, default: 'false', description: 'Mask characters with •' },
      { name: 'multiline', type: "boolean", required: false, default: 'false', description: 'Allow multiple lines' },
      { name: 'wordWrap', type: "boolean", required: false, default: 'false', description: 'Wrap text at the input width' },
      { name: 'width', type: "number", required: false, default: '80', description: 'Input width in characters' },
      { name: 'maxLines', type: "number", required: false, description: 'Maximum visible lines before scrolling' },
      { name: 'autoGrow', type: "boolean", required: false, default: 'false', description: 'Grow height based on visual line count (up to maxLines, defaults to 5)' },
      { name: 'showScrollbar', type: "boolean", required: false, default: 'true', description: 'Show scrollbar when content exceeds maxLines' },
      { name: 'initialSegments', type: "TextInputSegment[]", required: false, description: 'Initial semantic prompt segments' },
      { name: 'onSegmentsChange', type: "(segments: TextInputSegment[]) => void", required: false, description: 'Called when segment ranges change' },
      { name: 'transformPaste', type: "(context) => TextInputInsertionLike", required: false, description: 'Transform pasted text into text or semantic segments before insertion' },
      { name: 'completion', type: "TextInputCompletionOptions", required: false, description: 'Anchored async completion provider' },
      { name: 'maxLength', type: "number", required: false, description: 'Maximum input length' },
      { name: 'history', type: "Array<string | TextInputHistoryEntry>", required: false, description: 'Optional prompt history entries for Up/Down navigation' },
      { name: 'historyPersistence', type: "TextInputHistoryPersistenceOptions", required: false, description: 'Optional synchronous persistence for submitted prompt history' },
      { name: 'focused', type: "boolean", required: false, default: 'false', description: 'Focus state (shows cursor)' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable input' },
      { name: 'cursorColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Cursor color' },
      { name: 'isActive', type: "boolean | (() => boolean)", required: false, default: 'true', description: 'Enable keyboard handling (supports reactive getter)' },
    ],
    examples: [
      `TextInput({ value: name(), onChange: setName, placeholder: 'Enter name' })`,
      `// Password input\nTextInput({\n  password: true,\n  placeholder: 'Enter password',\n  onSubmit: handleLogin,\n})`,
      `// Canonical rerender-safe path\nconst message = useTextInputState({\n  multiline: true,\n  wordWrap: true,\n  autoGrow: true,\n  maxLines: 5,\n  showScrollbar: true,\n  placeholder: 'Type your message...',\n});\n\nTextInput({\n  state: message,\n  borderStyle: 'round',\n  fullWidth: true,\n})`,
      `// Advanced explicit-state path\nconst input = createTextInput({\n  history: ['help', 'status'],\n  onSubmit: (cmd) => runCommand(cmd),\n});\nrenderTextInput(input, { borderStyle: 'round' })`,
      `// Composable prompt completions: @ files, # issues, and ~/ paths\nconst completion = createComposableCompletion([\n  createTriggerCompletionSource({ trigger: '@', getItems: searchProjectFiles, segmentKind: 'file' }),\n  createTriggerCompletionSource({ trigger: '#', getItems: searchIssues, insertAsSegment: false }),\n  createPathCompletionSource({ cwd: process.cwd(), maxItems: 30 }),\n]);\n\nconst prompt = useTextInputState({ completion });\nTextInput({ state: prompt, fullWidth: true });`,
      `// Collapse large pasted logs/code into a semantic segment\nconst pasteCollapse = createPasteCollapseTransform({\n  minChars: 500,\n  minLines: 3,\n  segmentKind: 'paste',\n});\nconst prompt = useTextInputState({\n  transformPaste: pasteCollapse,\n});\n\nTextInput({ state: prompt, fullWidth: true });\n\nconst pasted = prompt.segments()\n  .filter((segment) => segment.kind === 'paste')\n  .map((segment) => pasteCollapse.store.get(segment.payload.pasteId));`,
      `// Composer submit policy: completion first, continuation newline, busy queue\nconst prompt = useTextInputState({ multiline: true });\nconst submit = createPromptSubmitController({\n  input: prompt,\n  busyPolicy: 'queue',\n  isBusy: () => busy(),\n  onInterrupt: () => currentTask()?.cancel('Interrupted'),\n  onSubmit: ({ value, segments, queued }) => runPrompt({ value, segments, queued }),\n});\nprompt.updateOptions({ onSubmit: () => submit.submit() });\n\nTextInput({ state: prompt, fullWidth: true });\nsubmit.queueDepth();\nconst next = submit.dequeue();\nif (next.action === 'dequeued') submit.submitQueued(next.item);`,
      `// Structured prompt path\nconst rankingStorage = createNodeFsSyncStorage({ dir: './.prompt-state' });\nconst promptHistoryStorage = createNodeFsSyncStorage({ dir: './.prompt-state' });\nconst promptModes = createPromptModeRegistry({\n  defaultMode: { id: 'text', label: 'Text' },\n  modes: [\n    { id: 'command', label: 'Command', prefix: '/' },\n    { id: 'shell', label: 'Shell', prefix: '!' },\n  ],\n});\nconst promptCommands = createPromptCommandRegistry([\n  { id: 'help', command: 'help', description: 'List available commands.', usage: '/help' },\n  { id: 'clear', command: 'clear', description: 'Reset the transcript.', usage: '/clear' },\n  {\n    id: 'seed',\n    command: 'seed',\n    description: 'Seed the prompt with semantic tokens.',\n    usage: '/seed <preset>',\n    getLiveDiagnostic: (context) => {\n      const preset = context.args[0];\n      if (!preset) return { level: 'warning', message: 'Preset required.' };\n      if (!['planner', 'reviewer'].includes(preset)) {\n        return { level: 'error', message: \`Unknown preset: \${preset}\` };\n      }\n      return { level: 'info', message: \`Preset ready: \${preset}\` };\n    },\n    completeArgs: (context) => ['planner', 'reviewer']\n      .filter((item) => item.includes(context.currentArgText))\n      .map((item) => ({ id: item, label: item, replacement: item })),\n  },\n]);\nconst prompt = useTextInputState({\n  history: [\n    {\n      value: '@research',\n      segments: [\n        { id: 'seed-research', kind: 'mention', start: 0, end: 9, displayText: '@research', payload: { agent: 'research' } },\n      ],\n    },\n  ],\n  historyPersistence: {\n    storage: promptHistoryStorage,\n    key: 'rich-prompt-history',\n    limit: 20,\n  },\n  transformPaste: ({ text }) => text.length > 80\n    ? {\n        parts: [\n          { type: 'text', text: 'Review ' },\n          { type: 'segment', segment: { kind: 'paste', displayText: \`[paste:\${text.length}c]\`, payload: { text } } },\n        ],\n      }\n    : undefined,\n  completion: {\n    resolveAnchor: ({ value, cursorPosition }) => {\n      const slashContext = promptCommands.getCompletionContext(value, cursorPosition);\n      if (slashContext) {\n        return { start: slashContext.replaceRange.start, end: slashContext.replaceRange.end, query: slashContext.query, trigger: '/' };\n      }\n      const match = value.slice(0, cursorPosition).match(/(?:^|\\s)([@#])([\\w./-]*)$/);\n      if (!match || match.index === undefined) return null;\n      const start = match[0].startsWith(' ') ? match.index + 1 : match.index;\n      return { start, end: cursorPosition, query: match[2] ?? '', trigger: match[1] };\n    },\n    getItems: ({ anchor }) => {\n      if (anchor.trigger === '/') {\n        return Promise.resolve(promptCommands.resolvePromptCompletion(prompt.value(), prompt.cursorPosition()))\n          .then((resolved) => resolved?.items.map((command) => ({\n            id: command.id,\n            label: command.label,\n            detail: command.detail,\n            replacement: command.replacement,\n          })) ?? []);\n      }\n      return executor.submit({\n        type: 'suggestPromptRefs',\n        payload: { trigger: anchor.trigger, query: anchor.query },\n      });\n    },\n    ranking: {\n      getKey: (item, context) => \`\${context.anchor.trigger ?? ''}:\${item.id}\`,\n      persistence: {\n        storage: rankingStorage,\n        key: 'rich-prompt-ranking',\n      },\n    },\n  },\n});\n\nconst mode = promptModes.inspectPrompt(prompt.value());\nconst completion = prompt.completion();\nconst slashContext = promptCommands.inspectPrompt(prompt.value(), prompt.cursorPosition());\ncompletion?.statusText;\ncompletion?.progress;\nprompt.getCompletionRankingSnapshot();\npromptModes.inspectPrompt('!git status');\npromptCommands.parse('/seed reviewer');\nmode.mode.id;\nslashContext?.status === 'matched' ? slashContext.diagnostic?.message : undefined;`,
      `// Background task progress with batched ingress\nconst app = useApp();\nconst task = executor.submit({ type: 'analyzePrompt', payload: { text: prompt.value() } });\nconst unsubscribe = task.subscribe((event) => {\n  if (event.kind !== 'progress') return;\n  app.enqueueExternalUpdate?.(() => {\n    setStatus(String((event.payload as { status?: string }).status ?? 'Working'));\n  });\n});\nconst result = await task.result;\nunsubscribe();`,
      `// Click-to-caret: clicking positions cursor at click location\n// Up/Down arrow: navigate between visual lines in multiline mode`,
    ],
    relatedComponents: ['Switch', 'Slider', 'Select', 'SearchInput', 'PasswordInput'],
  },
  {
    name: 'Switch',
    category: 'atoms',
    description: 'Toggle switch with on/off states. Supports labels, custom colors, and sizes.',
    props: [
      { name: 'initialValue', type: "boolean", required: false, default: 'false', description: 'Initial on/off state' },
      { name: 'onLabel', type: "string", required: false, default: "'ON'", description: 'Label when on' },
      { name: 'offLabel', type: "string", required: false, default: "'OFF'", description: 'Label when off' },
      { name: 'showLabels', type: "boolean", required: false, default: 'true', description: 'Show on/off labels' },
      { name: 'onColor', type: "ColorValue", required: false, default: "'green'", description: 'Color when on' },
      { name: 'offColor', type: "ColorValue", required: false, default: "'gray'", description: 'Color when off' },
      { name: 'size', type: "'small' | 'medium' | 'large'", required: false, default: "'medium'", description: 'Switch size' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'onChange', type: "(value: boolean) => void", required: false, description: 'Change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "SwitchState", required: false, description: 'External state from createSwitch()' },
    ],
    examples: [
      `Switch({ onChange: (on) => console.log(on) })`,
      `// With custom labels\nSwitch({\n  onLabel: 'Enabled',\n  offLabel: 'Disabled',\n  onColor: 'cyan',\n})`,
      `// Controlled with createSwitch\nconst sw = createSwitch({ initialValue: true });\nsw.toggle();\n\nSwitch({ state: sw })`,
    ],
    relatedComponents: ['ToggleGroup', 'Checkbox', 'RadioGroup'],
  },
  {
    name: 'ToggleGroup',
    category: 'atoms',
    description: 'Group of multiple toggle switches with shared state management.',
    props: [
      { name: 'options', type: "ToggleOption[]", required: true, description: 'Array of { key, label, initialValue?, disabled? }' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'vertical'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, default: '1', description: 'Gap between toggles' },
      { name: 'onChange', type: "(values: Record<string, boolean>) => void", required: false, description: 'Callback with all toggle values' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
    ],
    examples: [
      `ToggleGroup({\n  options: [\n    { key: 'darkMode', label: 'Dark Mode', initialValue: true },\n    { key: 'notifications', label: 'Notifications' },\n    { key: 'sounds', label: 'Sound Effects' },\n  ],\n  onChange: (values) => saveSettings(values),\n})`,
    ],
    relatedComponents: ['Switch', 'RadioGroup', 'MultiSelect'],
  },
  {
    name: 'Slider',
    category: 'atoms',
    description: 'Range slider for numeric values. Shows value and optional min/max labels.',
    props: [
      { name: 'min', type: "number", required: false, default: '0', description: 'Minimum value' },
      { name: 'max', type: "number", required: false, default: '100', description: 'Maximum value' },
      { name: 'step', type: "number", required: false, default: '1', description: 'Step increment' },
      { name: 'initialValue', type: "number", required: false, description: 'Initial value (defaults to min)' },
      { name: 'width', type: "number", required: false, default: '20', description: 'Slider width' },
      { name: 'showValue', type: "boolean", required: false, default: 'true', description: 'Show current value' },
      { name: 'showMinMax', type: "boolean", required: false, default: 'false', description: 'Show min/max labels' },
      { name: 'formatValue', type: "(value: number) => string", required: false, description: 'Value formatter function' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Slider fill color' },
      { name: 'onChange', type: "(value: number) => void", required: false, description: 'Change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "SliderState", required: false, description: 'External state from createSlider()' },
    ],
    examples: [
      `Slider({ min: 0, max: 100, onChange: setVolume })`,
      `// With percentage formatting\nSlider({\n  min: 0,\n  max: 1,\n  step: 0.1,\n  formatValue: (v) => \`\${Math.round(v * 100)}%\`,\n})`,
    ],
    relatedComponents: ['RangeSlider', 'ProgressBar'],
  },
  {
    name: 'RangeSlider',
    category: 'atoms',
    description: 'Dual-thumb slider for selecting a range of values.',
    props: [
      { name: 'min', type: "number", required: false, default: '0', description: 'Minimum value' },
      { name: 'max', type: "number", required: false, default: '100', description: 'Maximum value' },
      { name: 'step', type: "number", required: false, default: '1', description: 'Step increment' },
      { name: 'initialValue', type: "[number, number]", required: false, description: 'Initial range [start, end]' },
      { name: 'width', type: "number", required: false, default: '20', description: 'Slider width' },
      { name: 'showValue', type: "boolean", required: false, default: 'true', description: 'Show current values' },
      { name: 'formatValue', type: "(value: number) => string", required: false, description: 'Value formatter' },
      { name: 'rangeColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Selected range color' },
      { name: 'trackColor', type: "ColorValue", required: false, default: "'gray'", description: 'Track color' },
      { name: 'onChange', type: "(range: [number, number]) => void", required: false, description: 'Change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
    ],
    examples: [
      `RangeSlider({\n  min: 0,\n  max: 1000,\n  initialValue: [200, 800],\n  onChange: ([min, max]) => setPriceRange(min, max),\n})`,
      `// With formatting\nRangeSlider({\n  min: 0,\n  max: 24,\n  formatValue: (h) => \`\${h}:00\`,\n  onChange: setTimeRange,\n})`,
    ],
    relatedComponents: ['Slider'],
  },

  // =============================================================================
  // Progress & Feedback
  // =============================================================================
  {
    name: 'ProgressBar',
    category: 'atoms',
    description: 'Progress indicator with multiple styles, percentage, ETA, and indeterminate mode.',
    props: [
      { name: 'value', type: "number", required: false, default: '0', description: 'Progress value (0-1 or 0-100)' },
      { name: 'max', type: "number", required: false, default: '100', description: 'Maximum value' },
      { name: 'width', type: "number", required: false, default: '20', description: 'Bar width in characters' },
      { name: 'style', type: "'block' | 'smooth' | 'line' | 'dots' | 'braille' | 'ascii'", required: false, default: "'block'", description: 'Visual style' },
      { name: 'showPercentage', type: "boolean", required: false, default: 'false', description: 'Show percentage text' },
      { name: 'showValue', type: "boolean", required: false, default: 'false', description: 'Show value (e.g., "50/100")' },
      { name: 'showEta', type: "boolean", required: false, default: 'false', description: 'Show estimated time remaining' },
      { name: 'showSpeed', type: "boolean", required: false, default: 'false', description: 'Show speed/rate' },
      { name: 'speedUnit', type: "string", required: false, description: 'Speed unit (e.g., "MB/s")' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Fill color' },
      { name: 'emptyColor', type: "ColorValue", required: false, default: "'gray'", description: 'Empty bar color' },
      { name: 'gradient', type: "string[]", required: false, description: 'Gradient colors array' },
      { name: 'label', type: "string", required: false, description: 'Label (left side)' },
      { name: 'description', type: "string", required: false, description: 'Description (right side)' },
      { name: 'indeterminate', type: "boolean", required: false, default: 'false', description: 'Unknown progress mode' },
      { name: 'borderStyle', type: "'none' | 'brackets' | 'pipes' | 'arrows'", required: false, default: "'none'", description: 'Border style' },
    ],
    examples: [
      `ProgressBar({ value: 75, width: 30, showPercentage: true })`,
      `// Download progress with ETA\nProgressBar({\n  value: downloaded,\n  max: totalSize,\n  label: 'Downloading',\n  showPercentage: true,\n  showEta: true,\n  showSpeed: true,\n  speedUnit: 'MB/s',\n})`,
      `// Indeterminate loading\nProgressBar({ indeterminate: true, label: 'Loading...' })`,
    ],
    relatedComponents: ['MultiProgressBar', 'Spinner'],
  },
  {
    name: 'MultiProgressBar',
    category: 'atoms',
    description: 'Multiple progress bars with segment support for parallel tasks.',
    props: [
      { name: 'bars', type: "ProgressBarOptions[]", required: true, description: 'Array of progress bar configurations' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'vertical'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, default: '0', description: 'Gap between bars' },
    ],
    examples: [
      `MultiProgressBar({\n  bars: [\n    { label: 'File 1', value: 100, color: 'green' },\n    { label: 'File 2', value: 65, color: 'cyan' },\n    { label: 'File 3', value: 30, color: 'yellow' },\n  ],\n})`,
    ],
    relatedComponents: ['ProgressBar'],
  },
  {
    name: 'Spinner',
    category: 'atoms',
    description: 'Animated loading spinner with 26+ styles.',
    props: [
      { name: 'style', type: "SpinnerStyle", required: false, default: "'dots'", description: 'Animation style (dots, line, circle, bounce, pong, hamburger, toggle, arrow, balloon, flip, noise, etc.)' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Spinner color' },
      { name: 'label', type: "string", required: false, description: 'Loading label text' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable animation' },
    ],
    examples: [
      `Spinner({ style: 'dots', label: 'Loading...' })`,
      `// Different styles\nSpinner({ style: 'bounce' })\nSpinner({ style: 'pong' })\nSpinner({ style: 'aesthetic' })\nSpinner({ style: 'dwarfFortress' })`,
    ],
    relatedComponents: ['ProgressBar', 'Timer'],
  },
  {
    name: 'Timer',
    category: 'atoms',
    description: 'Display formatted time for countdowns or stopwatches. Use with createTimer() for state.',
    props: [
      { name: 'time', type: "number", required: true, description: 'Time in milliseconds' },
      { name: 'format', type: "'ss' | 'mm:ss' | 'hh:mm:ss' | 'hh:mm:ss.ms' | 'human'", required: false, default: "'mm:ss'", description: 'Display format' },
      { name: 'color', type: "ColorValue", required: false, default: "'white'", description: 'Text color' },
      { name: 'running', type: "boolean", required: false, default: 'false', description: 'Timer is running' },
      { name: 'paused', type: "boolean", required: false, default: 'false', description: 'Timer is paused' },
      { name: 'runningIndicator', type: "string", required: false, default: "'●'", description: 'Running indicator icon' },
      { name: 'pausedIndicator', type: "string", required: false, default: "'❚❚'", description: 'Paused indicator icon' },
      { name: 'showIndicator', type: "boolean", required: false, default: 'true', description: 'Show status indicator' },
      { name: 'label', type: "string", required: false, description: 'Label prefix' },
      { name: 'bold', type: "boolean", required: false, default: 'true', description: 'Bold text' },
      { name: 'dimWhenPaused', type: "boolean", required: false, default: 'true', description: 'Dim when paused' },
    ],
    examples: [
      `// Stopwatch\nconst timer = createTimer({ mode: 'stopwatch' });\ntimer.start();\n\nTimer({\n  time: timer.elapsed(),\n  format: 'mm:ss',\n  running: timer.isRunning(),\n})`,
      `// Countdown with color change\nTimer({\n  time: countdown.remaining(),\n  format: 'mm:ss',\n  color: countdown.remaining() < 10000 ? 'red' : 'green',\n})`,
    ],
    relatedComponents: ['Spinner', 'ProgressBar'],
  },

  // =============================================================================
  // Visual Components
  // =============================================================================
  {
    name: 'Badge',
    category: 'atoms',
    description: 'Small badge/chip for status labels with multiple variants.',
    props: [
      { name: 'label', type: "string", required: false, default: "''", description: 'Badge label text' },
      { name: 'color', type: "ColorValue", required: false, default: "'mutedForeground'", description: 'Badge color' },
      { name: 'variant', type: "'solid' | 'outline' | 'subtle'", required: false, default: "'subtle'", description: 'Visual variant' },
    ],
    examples: [
      `Badge({ label: 'NEW', color: 'success' })`,
      `Badge({ label: '5', color: 'destructive', variant: 'solid' })`,
      `Badge({ label: 'Beta', variant: 'outline', color: 'primary' })`,
    ],
    relatedComponents: ['Tag', 'Tooltip'],
  },
  {
    name: 'Tag',
    category: 'atoms',
    description: 'Labeled tag with optional remove button for tagging/filtering.',
    props: [
      { name: 'label', type: "string", required: true, description: 'Tag label text' },
      { name: 'color', type: "ColorValue", required: false, default: "'mutedForeground'", description: 'Tag color' },
      { name: 'removable', type: "boolean", required: false, default: 'false', description: 'Show remove button' },
      { name: 'onRemove', type: "() => void", required: false, description: 'Remove callback' },
    ],
    examples: [
      `Tag({ label: 'TypeScript', color: 'accent' })`,
      `// Removable tags\nEach(tags, (tag) =>\n  Tag({\n    label: tag,\n    removable: true,\n    onRemove: () => removeTag(tag),\n  })\n)`,
    ],
    relatedComponents: ['Badge', 'TagInput'],
  },
  {
    name: 'Tooltip',
    category: 'atoms',
    description: 'Tooltip with arrow pointing to content. Supports all positions.',
    props: [
      { name: 'content', type: "string | VNode", required: true, description: 'Tooltip content' },
      { name: 'position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'top'", description: 'Position relative to target' },
      { name: 'arrow', type: "boolean", required: false, default: 'true', description: 'Show arrow pointer' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'round'", description: 'Border style' },
      { name: 'borderColor', type: "ColorValue", required: false, default: "'border'", description: 'Border color' },
      { name: 'color', type: "ColorValue", required: false, default: "'foreground'", description: 'Text color' },
      { name: 'backgroundColor', type: "ColorValue", required: false, description: 'Background color' },
      { name: 'visible', type: "boolean", required: false, default: 'true', description: 'Visibility state' },
      { name: 'maxWidth', type: "number", required: false, description: 'Maximum width' },
    ],
    examples: [
      `Tooltip({ content: 'Press Enter to confirm', position: 'bottom' })`,
      `// Rich tooltip\nTooltip({\n  content: VStack({},\n    Text({ bold: true }, 'Shortcuts'),\n    Text({}, 'Ctrl+S: Save'),\n  ),\n  position: 'right',\n})`,
    ],
    relatedComponents: ['WithTooltip', 'helpTooltip', 'Popover'],
  },
  {
    name: 'WithTooltip',
    category: 'atoms',
    description: 'Wrapper that shows tooltip when element is active/focused.',
    props: [
      { name: 'children', type: "VNode", required: true, description: 'Target element' },
      { name: 'tooltip', type: "string | VNode", required: true, description: 'Tooltip content' },
      { name: 'position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'top'", description: 'Tooltip position' },
      { name: 'active', type: "boolean", required: false, default: 'false', description: 'Show tooltip when true' },
      { name: 'tooltipProps', type: "Partial<TooltipOptions>", required: false, description: 'Additional tooltip props' },
    ],
    examples: [
      `WithTooltip({\n  children: Button({ label: 'Submit' }),\n  tooltip: 'Press Enter to submit the form',\n  position: 'top',\n  active: isFocused,\n})`,
    ],
    relatedComponents: ['Tooltip', 'helpTooltip'],
  },
  {
    name: 'helpTooltip',
    category: 'atoms',
    description: 'Help icon [?] that shows tooltip when active. Factory function for easy creation.',
    props: [
      { name: 'text', type: "string", required: true, description: 'Help text (first parameter)' },
      { name: 'options.position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'right'", description: 'Tooltip position' },
      { name: 'options.active', type: "boolean", required: false, default: 'false', description: 'Show tooltip when true' },
      { name: 'options.icon', type: "string", required: false, default: "'?'", description: 'Help icon character' },
      { name: 'options.iconColor', type: "ColorValue", required: false, default: "'primary'", description: 'Icon color' },
    ],
    examples: [
      `// Next to form field\nBox({ flexDirection: 'row', gap: 1 },\n  Text({}, 'Email:'),\n  helpTooltip('Enter your email address', { active: emailFocused }),\n)`,
    ],
    relatedComponents: ['Tooltip', 'WithTooltip', 'InfoBox'],
  },
  {
    name: 'InfoBox',
    category: 'atoms',
    description: 'Information callout box for tips, warnings, and errors.',
    props: [
      { name: 'message', type: "string | VNode", required: true, description: 'Message content' },
      { name: 'type', type: "'info' | 'warning' | 'error' | 'success' | 'tip'", required: false, default: "'info'", description: 'Box type (affects colors and icon)' },
      { name: 'title', type: "string", required: false, description: 'Optional title' },
      { name: 'showIcon', type: "boolean", required: false, default: 'true', description: 'Show type icon' },
      { name: 'width', type: "number", required: false, description: 'Fixed width' },
    ],
    examples: [
      `InfoBox({ type: 'warning', title: 'Caution', message: 'This action cannot be undone.' })`,
      `InfoBox({ type: 'tip', message: 'Press Tab to autocomplete' })`,
      `InfoBox({ type: 'error', message: 'Connection failed. Retrying...' })`,
    ],
    relatedComponents: ['Toast', 'AlertBox'],
  },
  {
    name: 'Popover',
    category: 'atoms',
    description: 'Positioned popover content box for menus and dropdowns.',
    props: [
      { name: 'content', type: "VNode", required: true, description: 'Popover content' },
      { name: 'position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'bottom'", description: 'Position relative to trigger' },
      { name: 'visible', type: "boolean", required: false, default: 'true', description: 'Visibility state' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'round'", description: 'Border style' },
      { name: 'borderColor', type: "ColorValue", required: false, default: "'border'", description: 'Border color' },
      { name: 'width', type: "number", required: false, description: 'Fixed width' },
      { name: 'arrow', type: "boolean", required: false, default: 'true', description: 'Show arrow' },
    ],
    examples: [
      `Popover({\n  content: VStack({},\n    Text({}, 'Option 1'),\n    Text({}, 'Option 2'),\n    Text({}, 'Option 3'),\n  ),\n  position: 'bottom',\n  visible: menuOpen(),\n  width: 20,\n})`,
    ],
    relatedComponents: ['Tooltip', 'Modal', 'CommandPalette'],
  },
  {
    name: 'BigText',
    category: 'atoms',
    description: 'Large ASCII art text with multiple font styles and gradient support.',
    props: [
      { name: 'text', type: "string", required: true, description: 'Text to display' },
      { name: 'font', type: "'block' | 'slant' | 'small' | 'standard' | 'banner' | 'mini' | 'shadow' | 'doom' | 'graffiti'", required: false, default: "'block'", description: 'Font style' },
      { name: 'color', type: "ColorValue", required: false, default: "'white'", description: 'Text color' },
      { name: 'gradient', type: "ColorValue[]", required: false, description: 'Gradient colors (per character)' },
      { name: 'align', type: "'left' | 'center' | 'right'", required: false, default: "'left'", description: 'Alignment' },
      { name: 'maxWidth', type: "number", required: false, description: 'Max width for alignment' },
      { name: 'letterSpacing', type: "number", required: false, default: '1', description: 'Spacing between letters' },
    ],
    examples: [
      `BigText({ text: 'HELLO', font: 'block', color: 'cyan' })`,
      `// Rainbow gradient\nBigText({\n  text: 'RAINBOW',\n  font: 'banner',\n  gradient: ['red', 'yellow', 'green', 'cyan', 'blue', 'magenta'],\n})`,
    ],
  },
  {
    name: 'Canvas',
    category: 'atoms',
    description: '2D drawing canvas for terminal. Supports character, braille (2x4), and block (2x2) modes with per-pixel color storage.',
    props: [
      { name: 'width', type: "number", required: true, description: 'Canvas width in characters' },
      { name: 'height', type: "number", required: true, description: 'Canvas height in characters' },
      { name: 'mode', type: "'character' | 'braille' | 'block'", required: false, default: "'character'", description: 'Drawing mode (braille has 8x resolution)' },
      { name: 'foreground', type: "ColorValue", required: false, description: 'Default foreground color' },
      { name: 'background', type: "ColorValue", required: false, description: 'Background color' },
      { name: 'fillChar', type: "string", required: false, default: "'█'", description: 'Fill character' },
      { name: 'defaultColor', type: "ColorValue", required: false, description: 'Default color for pixels when color not specified' },
    ],
    methods: [
      { name: 'setPixel(x, y, char, color?)', description: 'Set pixel character with optional color. The 4th parameter stores color per-pixel.' },
      { name: 'getPixel(x, y)', description: 'Get pixel character at position' },
      { name: 'getPixelColor(x, y)', description: 'Get color at position (returns undefined if not set)' },
      { name: 'setPixelColor(x, y, color)', description: 'Set color at position without changing character' },
      { name: 'render()', description: 'Render canvas to string[] with ANSI colors applied per-pixel' },
      { name: 'renderLine(y)', description: 'Render single line with ANSI colors' },
      { name: 'clear()', description: 'Clear canvas (resets both characters and colors)' },
      { name: 'line(x1, y1, x2, y2)', description: 'Draw line using Bresenham algorithm' },
      { name: 'circle(cx, cy, r)', description: 'Draw circle outline' },
      { name: 'fillCircle(cx, cy, r)', description: 'Draw filled circle' },
      { name: 'rect(x, y, w, h)', description: 'Draw rectangle outline' },
      { name: 'fillRect(x, y, w, h)', description: 'Draw filled rectangle' },
    ],
    examples: [
      `const canvas = createCanvas({ width: 40, height: 20, mode: 'braille' });\ncanvas.line(0, 0, 39, 19);\ncanvas.circle(20, 10, 8);\nconst output = canvas.render();`,
      `// Per-pixel color support\nconst canvas = createCanvas({ width: 80, height: 24 });\ncanvas.setPixel(10, 5, '█', 'red');      // Red pixel\ncanvas.setPixel(11, 5, '█', '#00ff00');  // Green pixel (hex)\ncanvas.setPixel(12, 5, '█', 'blue-500'); // Blue pixel (palette)\n\n// render() returns ANSI-colored strings\nconst lines = canvas.render();\nlines.forEach(line => Text({}, line));`,
      `// Paint application pattern\nconst [color, setColor] = useState('cyan');\nconst canvas = createCanvas({ width: 80, height: 24 });\n\nuseLocalMouse(bounds, (event) => {\n  if (event.isInside && (event.action === 'click' || event.action === 'drag')) {\n    canvas.setPixel(event.x, event.y, '█', color());\n    rerender();\n  }\n});\n\n// Color picker - read existing colors\nconst existingColor = canvas.getPixelColor(x, y);\nif (existingColor) {\n  // Pixel has a color\n}`,
    ],
  },
  {
    name: 'Scrollbar',
    category: 'atoms',
    description: 'Standalone scrollbar for custom scroll implementations.',
    props: [
      { name: 'height', type: "number", required: true, description: 'Height of scrollbar area (lines)' },
      { name: 'total', type: "number", required: true, description: 'Total content height' },
      { name: 'current', type: "number", required: true, description: 'Current scroll position' },
      { name: 'color', type: "ColorValue", required: false, default: "'primary'", description: 'Thumb color (theme-aware)' },
      { name: 'trackColor', type: "ColorValue", required: false, default: "'muted'", description: 'Track color (theme-aware)' },
      { name: 'thumbChar', type: "string", required: false, description: 'Custom thumb character' },
      { name: 'trackChar', type: "string", required: false, description: 'Custom track character' },
    ],
    examples: [
      `Scrollbar({ height: 10, total: 50, current: 15 })`,
      `// Custom styled\nBox({ flexDirection: 'row' },\n  Box({ width: 40 }, ...content),\n  Scrollbar({ height: 10, total: 100, current: scrollTop() }),\n)`,
    ],
    relatedComponents: ['ScrollArea', 'ScrollList'],
  },

  // =============================================================================
  // Status & Metrics Components
  // =============================================================================
  {
    name: 'StatusIndicator',
    category: 'atoms',
    description: 'Semantic status display with color-coded icons, optional pulse animation, and preset factories.',
    props: [
      { name: 'status', type: "BuiltInStatus | CustomStatus", required: true, description: "Status type: 'success' | 'warning' | 'error' | 'info' | 'pending' | 'running' | 'stopped' or { color, icon }" },
      { name: 'label', type: 'MaybeReactive<string>', required: false, description: 'Optional text label after indicator' },
      { name: 'showIcon', type: 'boolean', required: false, default: 'true', description: 'Display status icon' },
      { name: 'showDot', type: 'boolean', required: false, default: 'false', description: 'Display colored dot instead of icon' },
      { name: 'size', type: "'sm' | 'md' | 'lg'", required: false, default: "'md'", description: 'Size variant' },
      { name: 'pulse', type: 'boolean', required: false, description: "Enable pulse animation (auto-enabled for 'running')" },
      { name: 'gap', type: 'number', required: false, default: '1', description: 'Gap between icon and label' },
    ],
    examples: [
      `// Built-in statuses\nStatusIndicator({ status: 'success', label: 'Connected' })\nStatusIndicator({ status: 'running', label: 'Processing...', pulse: true })\nStatusIndicator({ status: 'error', label: 'Failed' })`,
      `// Preset factories (shortcuts)\nimport { loadingStatus, successStatus, errorStatus } from 'tuiuiu.js'\n\nStatusIndicator(loadingStatus('Processing...'))\nStatusIndicator(successStatus('Done'))\nStatusIndicator(errorStatus('Connection failed'))`,
      `// Custom status\nStatusIndicator({\n  status: { color: 'magenta', icon: '◆' },\n  label: 'Custom Status',\n})`,
      `// Reactive status\nStatusIndicator({\n  status: () => isConnected() ? 'success' : 'error',\n  label: () => isConnected() ? 'Online' : 'Offline',\n})`,
    ],
    relatedComponents: ['Badge', 'InfoBox', 'MetricDisplay'],
  },
  {
    name: 'MetricDisplay',
    category: 'atoms',
    description: 'Dashboard metric component with value, trend sparkline, delta percentage, and threshold-based coloring. Use createMetric() for auto-tracking state.',
    props: [
      { name: 'metric', type: 'MetricState', required: false, description: 'State from createMetric() - preferred for reactive metrics' },
      { name: 'label', type: 'MaybeReactive<string>', required: false, description: 'Metric label (standalone mode)' },
      { name: 'value', type: 'MaybeReactive<number>', required: false, description: 'Current value (standalone mode)' },
      { name: 'unit', type: 'MaybeReactive<string>', required: false, description: "Unit suffix (e.g., '%', 'ms', 'MB')" },
      { name: 'trend', type: 'MaybeReactive<number[]>', required: false, description: 'Historical data for sparkline' },
      { name: 'trendWidth', type: 'number', required: false, default: '10', description: 'Sparkline width in chars' },
      { name: 'delta', type: 'MaybeReactive<number>', required: false, description: 'Delta percentage (auto-calculated with createMetric)' },
      { name: 'thresholds', type: 'ExtendedThresholdConfig', required: false, description: 'Threshold config for value coloring' },
      { name: 'layout', type: "'horizontal' | 'vertical'", required: false, default: "'horizontal'", description: 'Layout direction' },
      { name: 'size', type: "'compact' | 'normal' | 'large'", required: false, default: "'normal'", description: 'Size variant' },
      { name: 'showTrend', type: 'boolean', required: false, default: 'true', description: 'Show sparkline trend' },
      { name: 'showDelta', type: 'boolean', required: false, default: 'true', description: 'Show delta indicator' },
    ],
    examples: [
      `// With createMetric() - auto-tracking (recommended)\nconst cpu = createMetric({\n  label: 'CPU',\n  unit: '%',\n  historySize: 20,\n  thresholds: {\n    success: [0, 50],\n    warning: [50, 80],\n    error: [80, 100],\n  },\n});\n\n// Update - history and delta auto-calculated!\ncpu.set(45);\ncpu.set(52);  // delta = +15.5%\n\nMetricDisplay({ metric: cpu })`,
      `// Standalone mode (one-off usage)\nMetricDisplay({\n  label: 'Response Time',\n  value: 145,\n  unit: 'ms',\n  trend: [120, 130, 145, 142, 145],\n  delta: 2.1,\n  thresholds: { success: [0, 200], error: [200, Infinity] },\n})`,
      `// Vertical layout\nMetricDisplay({ metric: cpu, layout: 'vertical' })`,
      `// Multiple metrics dashboard\nBox({ flexDirection: 'row', gap: 4 },\n  MetricDisplay({ metric: cpuMetric }),\n  MetricDisplay({ metric: memoryMetric }),\n  MetricDisplay({ metric: requestsMetric }),\n)`,
    ],
    relatedComponents: ['StatusIndicator', 'ProgressBar', 'Sparkline', 'Gauge'],
  },
  {
    name: 'DataRow',
    category: 'atoms',
    description: 'Label-value row for details panels, inspectors, request summaries, and settings screens.',
    props: [
      { name: 'label', type: 'MaybeReactive<string>', required: true, description: 'Label shown on the left' },
      { name: 'value', type: 'MaybeReactive<string | number | VNode>', required: true, description: 'Value shown on the right' },
      { name: 'labelWidth', type: 'MaybeReactive<number>', required: false, description: 'Optional fixed label column width' },
      { name: 'labelColor', type: 'MaybeReactive<ColorValue>', required: false, description: 'Optional label color' },
      { name: 'valueColor', type: 'MaybeReactive<ColorValue>', required: false, description: 'Optional value color' },
      { name: 'status', type: 'MaybeReactive<StatusType>', required: false, description: 'Optional semantic status indicator' },
      { name: 'truncate', type: 'MaybeReactive<number>', required: false, description: 'Maximum value width before truncation' },
    ],
    examples: [
      `DataRow({ label: 'Host', value: 'api.example.com' })`,
      `DataRow({ label: 'Latency', value: '145ms', status: 'warning' })`,
      `DataRow({\n  label: 'Request ID',\n  value: () => currentRequest().id,\n  truncate: 24,\n})`,
    ],
    relatedComponents: ['ListItem', 'HttpStatus', 'StatusIndicator'],
  },
  {
    name: 'ListItem',
    category: 'atoms',
    description: 'Standardized list row with icon, primary/secondary text, trailing content, and selected state styling.',
    props: [
      { name: 'primary', type: 'MaybeReactive<string | number | VNode>', required: true, description: 'Primary content' },
      { name: 'secondary', type: 'MaybeReactive<string | number | VNode>', required: false, description: 'Secondary content below primary' },
      { name: 'icon', type: 'MaybeReactive<string | number | VNode>', required: false, description: 'Leading icon or glyph' },
      { name: 'trailing', type: 'MaybeReactive<string | number | VNode>', required: false, description: 'Trailing content' },
      { name: 'status', type: 'MaybeReactive<StatusType>', required: false, description: 'Optional semantic status indicator' },
      { name: 'selected', type: 'MaybeReactive<boolean>', required: false, default: 'false', description: 'Selected state' },
      { name: 'disabled', type: 'MaybeReactive<boolean>', required: false, default: 'false', description: 'Disabled styling' },
      { name: 'indent', type: 'MaybeReactive<number>', required: false, default: '0', description: 'Indentation level' },
    ],
    examples: [
      `ListItem({ icon: '📄', primary: 'README.md', secondary: '2.1 KB' })`,
      `ListItem({ primary: 'POST /api/orders', trailing: '145ms', selected: true })`,
      `ListItem({\n  primary: () => currentJob().name,\n  secondary: () => currentJob().owner,\n  status: () => currentJob().healthy ? 'success' : 'error',\n})`,
    ],
    relatedComponents: ['SplitView', 'DataRow', 'StatusIndicator'],
  },
  {
    name: 'HttpStatus',
    category: 'atoms',
    description: 'HTTP status code renderer with automatic color mapping and optional lookup text.',
    props: [
      { name: 'code', type: 'MaybeReactive<number>', required: true, description: 'HTTP status code' },
      { name: 'showText', type: 'boolean', required: false, default: 'false', description: 'Show lookup text such as "Not Found"' },
      { name: 'variant', type: "'badge' | 'text' | 'dot'", required: false, default: "'badge'", description: 'Visual style' },
    ],
    examples: [
      `HttpStatus({ code: 200 })`,
      `HttpStatus({ code: 404, showText: true, variant: 'text' })`,
      `Box({ flexDirection: 'row', gap: 1 }, httpOk(), httpNotFound(), httpError(503, true))`,
    ],
    relatedComponents: ['Badge', 'DataRow', 'StatusIndicator'],
  },
];
