/**
 * Atoms Documentation
 * Complete documentation for all atom-level components
 */

import type { ComponentDoc } from '../types.js';

export const atoms: ComponentDoc[] = [
  // =============================================================================
  // Button Components
  // =============================================================================
  {
    name: 'Button',
    category: 'atoms',
    description: 'Interactive button with multiple variants, sizes, loading states, and icon support.',
    props: [
      { name: 'label', type: "string", required: true, description: 'Button label text' },
      { name: 'onClick', type: "() => void", required: false, description: 'Click handler' },
      { name: 'variant', type: "'solid' | 'outline' | 'ghost' | 'link'", required: false, default: "'solid'", description: 'Visual variant' },
      { name: 'size', type: "'small' | 'medium' | 'large'", required: false, default: "'medium'", description: 'Button size' },
      { name: 'color', type: "ColorValue", required: false, description: 'Button color (uses theme accent by default)' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'loading', type: "boolean", required: false, default: 'false', description: 'Show loading spinner' },
      { name: 'loadingText', type: "string", required: false, description: 'Text to show while loading' },
      { name: 'icon', type: "string", required: false, description: 'Icon before label (emoji or character)' },
      { name: 'iconRight', type: "string", required: false, description: 'Icon after label' },
      { name: 'fullWidth', type: "boolean", required: false, default: 'false', description: 'Expand to fill container' },
      { name: 'focused', type: "boolean", required: false, default: 'false', description: 'Focus state (for keyboard nav)' },
      { name: 'hovered', type: "boolean", required: false, default: 'false', description: 'Hover state (from mouse)' },
    ],
    examples: [
      `Button({ label: 'Submit', onClick: () => console.log('clicked') })`,
      `// With icon and variant\nButton({\n  label: 'Save',\n  icon: '💾',\n  variant: 'solid',\n  color: 'success',\n  onClick: handleSave,\n})`,
      `// Loading state\nButton({\n  label: 'Submit',\n  loading: isSubmitting(),\n  loadingText: 'Submitting...',\n  onClick: handleSubmit,\n})`,
      `// Ghost button\nButton({ label: 'Cancel', variant: 'ghost' })`,
    ],
    relatedComponents: ['IconButton', 'ButtonGroup'],
  },
  {
    name: 'IconButton',
    category: 'atoms',
    description: 'Button with just an icon, no label. Ideal for toolbars and compact UI.',
    props: [
      { name: 'icon', type: "string", required: true, description: 'Icon to display (emoji or character)' },
      { name: 'label', type: "string", required: true, description: 'Accessibility label (not displayed)' },
      { name: 'onClick', type: "() => void", required: false, description: 'Click handler' },
      { name: 'color', type: "ColorValue", required: false, description: 'Icon color' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'focused', type: "boolean", required: false, default: 'false', description: 'Focus state' },
      { name: 'hovered', type: "boolean", required: false, default: 'false', description: 'Hover state' },
    ],
    examples: [
      `IconButton({ icon: '🗑️', label: 'Delete', onClick: handleDelete })`,
      `// Toolbar icons\nBox({ flexDirection: 'row', gap: 1 },\n  IconButton({ icon: '📁', label: 'Open' }),\n  IconButton({ icon: '💾', label: 'Save' }),\n  IconButton({ icon: '↩️', label: 'Undo' }),\n)`,
    ],
    relatedComponents: ['Button', 'ButtonGroup'],
  },
  {
    name: 'ButtonGroup',
    category: 'atoms',
    description: 'Group of buttons with **built-in keyboard navigation** - no useInput needed! **API Pattern: Data-Driven** - buttons are defined in a buttons array, NOT as children.',
    props: [
      { name: 'buttons', type: "ButtonProps[]", required: true, description: 'Array of { label, onClick, variant?, color?, disabled? }' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'horizontal'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, default: '1', description: 'Gap between buttons' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard navigation' },
      { name: 'wrap', type: "boolean", required: false, default: 'true', description: 'Wrap around at edges' },
      { name: 'onFocusChange', type: "(index: number) => void", required: false, description: 'Called when focus changes' },
    ],
    examples: [
      `// ✅ Out-of-the-box keyboard navigation\nButtonGroup({\n  buttons: [\n    { label: 'Save', onClick: save, variant: 'solid', color: 'success' },\n    { label: 'Cancel', onClick: cancel, variant: 'outline' },\n  ],\n})\n// Arrow keys navigate, Enter/Space triggers onClick!`,
      `// Keyboard: ← → (or ↑ ↓ for vertical), Enter/Space to click, h/j/k/l vim keys`,
    ],
    relatedComponents: ['Button', 'IconButton'],
  },

  // =============================================================================
  // Input Components
  // =============================================================================
  {
    name: 'TextInput',
    category: 'atoms',
    description: 'Single or multi-line text input with cursor, history, and password support.',
    props: [
      { name: 'value', type: "string", required: false, description: 'Current value (for controlled mode)' },
      { name: 'initialValue', type: "string", required: false, default: "''", description: 'Initial value' },
      { name: 'onChange', type: "(value: string) => void", required: false, description: 'Change handler' },
      { name: 'onSubmit', type: "(value: string) => void", required: false, description: 'Enter key handler' },
      { name: 'placeholder', type: "string", required: false, description: 'Placeholder text when empty' },
      { name: 'password', type: "boolean", required: false, default: 'false', description: 'Mask characters with •' },
      { name: 'multiline', type: "boolean", required: false, default: 'false', description: 'Allow multiple lines' },
      { name: 'wrap', type: "boolean", required: false, default: 'true', description: 'Wrap long lines (multiline only)' },
      { name: 'width', type: "number", required: false, default: '20', description: 'Input width in characters' },
      { name: 'maxLength', type: "number", required: false, description: 'Maximum input length' },
      { name: 'history', type: "boolean", required: false, default: 'false', description: 'Enable Up/Down history navigation' },
      { name: 'focused', type: "boolean", required: false, default: 'false', description: 'Focus state (shows cursor)' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable input' },
      { name: 'cursorColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Cursor color' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
    ],
    examples: [
      `TextInput({ value: name(), onChange: setName, placeholder: 'Enter name' })`,
      `// Password input\nTextInput({\n  password: true,\n  placeholder: 'Enter password',\n  onSubmit: handleLogin,\n})`,
      `// With history (like shell)\nconst input = createTextInput({\n  history: true,\n  onSubmit: (cmd) => runCommand(cmd),\n});\nTextInput(input.props)`,
    ],
    relatedComponents: ['Switch', 'Slider', 'Select'],
  },
  {
    name: 'Switch',
    category: 'atoms',
    description: 'Toggle switch with on/off states. Supports labels, custom colors, and sizes.',
    props: [
      { name: 'initialValue', type: "boolean", required: false, default: 'false', description: 'Initial on/off state' },
      { name: 'onLabel', type: "string", required: false, default: "'ON'", description: 'Label when on' },
      { name: 'offLabel', type: "string", required: false, default: "'OFF'", description: 'Label when off' },
      { name: 'showLabels', type: "boolean", required: false, default: 'true', description: 'Show on/off labels' },
      { name: 'onColor', type: "ColorValue", required: false, default: "'green'", description: 'Color when on' },
      { name: 'offColor', type: "ColorValue", required: false, default: "'gray'", description: 'Color when off' },
      { name: 'size', type: "'small' | 'medium' | 'large'", required: false, default: "'medium'", description: 'Switch size' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'onChange', type: "(value: boolean) => void", required: false, description: 'Change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "SwitchState", required: false, description: 'External state from createSwitch()' },
    ],
    examples: [
      `Switch({ onChange: (on) => console.log(on) })`,
      `// With custom labels\nSwitch({\n  onLabel: 'Enabled',\n  offLabel: 'Disabled',\n  onColor: 'cyan',\n})`,
      `// Controlled with createSwitch\nconst sw = createSwitch({ initialValue: true });\nsw.toggle();\n\nSwitch({ state: sw })`,
    ],
    relatedComponents: ['ToggleGroup', 'Checkbox', 'RadioGroup'],
  },
  {
    name: 'ToggleGroup',
    category: 'atoms',
    description: 'Group of multiple toggle switches with shared state management.',
    props: [
      { name: 'options', type: "ToggleOption[]", required: true, description: 'Array of { key, label, initialValue?, disabled? }' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'vertical'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, default: '1', description: 'Gap between toggles' },
      { name: 'onChange', type: "(values: Record<string, boolean>) => void", required: false, description: 'Callback with all toggle values' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
    ],
    examples: [
      `ToggleGroup({\n  options: [\n    { key: 'darkMode', label: 'Dark Mode', initialValue: true },\n    { key: 'notifications', label: 'Notifications' },\n    { key: 'sounds', label: 'Sound Effects' },\n  ],\n  onChange: (values) => saveSettings(values),\n})`,
    ],
    relatedComponents: ['Switch', 'RadioGroup', 'MultiSelect'],
  },
  {
    name: 'Slider',
    category: 'atoms',
    description: 'Range slider for numeric values. Shows value and optional min/max labels.',
    props: [
      { name: 'min', type: "number", required: false, default: '0', description: 'Minimum value' },
      { name: 'max', type: "number", required: false, default: '100', description: 'Maximum value' },
      { name: 'step', type: "number", required: false, default: '1', description: 'Step increment' },
      { name: 'initialValue', type: "number", required: false, description: 'Initial value (defaults to min)' },
      { name: 'width', type: "number", required: false, default: '20', description: 'Slider width' },
      { name: 'showValue', type: "boolean", required: false, default: 'true', description: 'Show current value' },
      { name: 'showMinMax', type: "boolean", required: false, default: 'false', description: 'Show min/max labels' },
      { name: 'formatValue', type: "(value: number) => string", required: false, description: 'Value formatter function' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Slider fill color' },
      { name: 'onChange', type: "(value: number) => void", required: false, description: 'Change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "SliderState", required: false, description: 'External state from createSlider()' },
    ],
    examples: [
      `Slider({ min: 0, max: 100, onChange: setVolume })`,
      `// With percentage formatting\nSlider({\n  min: 0,\n  max: 1,\n  step: 0.1,\n  formatValue: (v) => \`\${Math.round(v * 100)}%\`,\n})`,
    ],
    relatedComponents: ['RangeSlider', 'ProgressBar'],
  },
  {
    name: 'RangeSlider',
    category: 'atoms',
    description: 'Dual-thumb slider for selecting a range of values.',
    props: [
      { name: 'min', type: "number", required: false, default: '0', description: 'Minimum value' },
      { name: 'max', type: "number", required: false, default: '100', description: 'Maximum value' },
      { name: 'step', type: "number", required: false, default: '1', description: 'Step increment' },
      { name: 'initialValue', type: "[number, number]", required: false, description: 'Initial range [start, end]' },
      { name: 'width', type: "number", required: false, default: '20', description: 'Slider width' },
      { name: 'showValue', type: "boolean", required: false, default: 'true', description: 'Show current values' },
      { name: 'formatValue', type: "(value: number) => string", required: false, description: 'Value formatter' },
      { name: 'rangeColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Selected range color' },
      { name: 'trackColor', type: "ColorValue", required: false, default: "'gray'", description: 'Track color' },
      { name: 'onChange', type: "(range: [number, number]) => void", required: false, description: 'Change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
    ],
    examples: [
      `RangeSlider({\n  min: 0,\n  max: 1000,\n  initialValue: [200, 800],\n  onChange: ([min, max]) => setPriceRange(min, max),\n})`,
      `// With formatting\nRangeSlider({\n  min: 0,\n  max: 24,\n  formatValue: (h) => \`\${h}:00\`,\n  onChange: setTimeRange,\n})`,
    ],
    relatedComponents: ['Slider'],
  },

  // =============================================================================
  // Progress & Feedback
  // =============================================================================
  {
    name: 'ProgressBar',
    category: 'atoms',
    description: 'Progress indicator with multiple styles, percentage, ETA, and indeterminate mode.',
    props: [
      { name: 'value', type: "number", required: false, default: '0', description: 'Progress value (0-1 or 0-100)' },
      { name: 'max', type: "number", required: false, default: '100', description: 'Maximum value' },
      { name: 'width', type: "number", required: false, default: '20', description: 'Bar width in characters' },
      { name: 'style', type: "'block' | 'smooth' | 'line' | 'dots' | 'braille' | 'ascii'", required: false, default: "'block'", description: 'Visual style' },
      { name: 'showPercentage', type: "boolean", required: false, default: 'false', description: 'Show percentage text' },
      { name: 'showValue', type: "boolean", required: false, default: 'false', description: 'Show value (e.g., "50/100")' },
      { name: 'showEta', type: "boolean", required: false, default: 'false', description: 'Show estimated time remaining' },
      { name: 'showSpeed', type: "boolean", required: false, default: 'false', description: 'Show speed/rate' },
      { name: 'speedUnit', type: "string", required: false, description: 'Speed unit (e.g., "MB/s")' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Fill color' },
      { name: 'emptyColor', type: "ColorValue", required: false, default: "'gray'", description: 'Empty bar color' },
      { name: 'gradient', type: "string[]", required: false, description: 'Gradient colors array' },
      { name: 'label', type: "string", required: false, description: 'Label (left side)' },
      { name: 'description', type: "string", required: false, description: 'Description (right side)' },
      { name: 'indeterminate', type: "boolean", required: false, default: 'false', description: 'Unknown progress mode' },
      { name: 'borderStyle', type: "'none' | 'brackets' | 'pipes' | 'arrows'", required: false, default: "'none'", description: 'Border style' },
    ],
    examples: [
      `ProgressBar({ value: 75, width: 30, showPercentage: true })`,
      `// Download progress with ETA\nProgressBar({\n  value: downloaded,\n  max: totalSize,\n  label: 'Downloading',\n  showPercentage: true,\n  showEta: true,\n  showSpeed: true,\n  speedUnit: 'MB/s',\n})`,
      `// Indeterminate loading\nProgressBar({ indeterminate: true, label: 'Loading...' })`,
    ],
    relatedComponents: ['MultiProgressBar', 'Spinner'],
  },
  {
    name: 'MultiProgressBar',
    category: 'atoms',
    description: 'Multiple progress bars with segment support for parallel tasks.',
    props: [
      { name: 'bars', type: "ProgressBarOptions[]", required: true, description: 'Array of progress bar configurations' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'vertical'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, default: '0', description: 'Gap between bars' },
    ],
    examples: [
      `MultiProgressBar({\n  bars: [\n    { label: 'File 1', value: 100, color: 'green' },\n    { label: 'File 2', value: 65, color: 'cyan' },\n    { label: 'File 3', value: 30, color: 'yellow' },\n  ],\n})`,
    ],
    relatedComponents: ['ProgressBar'],
  },
  {
    name: 'Spinner',
    category: 'atoms',
    description: 'Animated loading spinner with 26+ styles.',
    props: [
      { name: 'style', type: "SpinnerStyle", required: false, default: "'dots'", description: 'Animation style (dots, line, circle, bounce, pong, hamburger, toggle, arrow, balloon, flip, noise, etc.)' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Spinner color' },
      { name: 'label', type: "string", required: false, description: 'Loading label text' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable animation' },
    ],
    examples: [
      `Spinner({ style: 'dots', label: 'Loading...' })`,
      `// Different styles\nSpinner({ style: 'bounce' })\nSpinner({ style: 'pong' })\nSpinner({ style: 'aesthetic' })\nSpinner({ style: 'dwarfFortress' })`,
    ],
    relatedComponents: ['ProgressBar', 'Timer'],
  },
  {
    name: 'Timer',
    category: 'atoms',
    description: 'Display formatted time for countdowns or stopwatches. Use with createTimer() for state.',
    props: [
      { name: 'time', type: "number", required: true, description: 'Time in milliseconds' },
      { name: 'format', type: "'ss' | 'mm:ss' | 'hh:mm:ss' | 'hh:mm:ss.ms' | 'human'", required: false, default: "'mm:ss'", description: 'Display format' },
      { name: 'color', type: "ColorValue", required: false, default: "'white'", description: 'Text color' },
      { name: 'running', type: "boolean", required: false, default: 'false', description: 'Timer is running' },
      { name: 'paused', type: "boolean", required: false, default: 'false', description: 'Timer is paused' },
      { name: 'runningIndicator', type: "string", required: false, default: "'●'", description: 'Running indicator icon' },
      { name: 'pausedIndicator', type: "string", required: false, default: "'❚❚'", description: 'Paused indicator icon' },
      { name: 'showIndicator', type: "boolean", required: false, default: 'true', description: 'Show status indicator' },
      { name: 'label', type: "string", required: false, description: 'Label prefix' },
      { name: 'bold', type: "boolean", required: false, default: 'true', description: 'Bold text' },
      { name: 'dimWhenPaused', type: "boolean", required: false, default: 'true', description: 'Dim when paused' },
    ],
    examples: [
      `// Stopwatch\nconst timer = createTimer({ mode: 'stopwatch' });\ntimer.start();\n\nTimer({\n  time: timer.elapsed(),\n  format: 'mm:ss',\n  running: timer.isRunning(),\n})`,
      `// Countdown with color change\nTimer({\n  time: countdown.remaining(),\n  format: 'mm:ss',\n  color: countdown.remaining() < 10000 ? 'red' : 'green',\n})`,
    ],
    relatedComponents: ['Spinner', 'ProgressBar'],
  },

  // =============================================================================
  // Visual Components
  // =============================================================================
  {
    name: 'Badge',
    category: 'atoms',
    description: 'Small badge/chip for status labels with multiple variants.',
    props: [
      { name: 'label', type: "string", required: false, default: "''", description: 'Badge label text' },
      { name: 'color', type: "ColorValue", required: false, default: "'mutedForeground'", description: 'Badge color' },
      { name: 'variant', type: "'solid' | 'outline' | 'subtle'", required: false, default: "'subtle'", description: 'Visual variant' },
    ],
    examples: [
      `Badge({ label: 'NEW', color: 'success' })`,
      `Badge({ label: '5', color: 'destructive', variant: 'solid' })`,
      `Badge({ label: 'Beta', variant: 'outline', color: 'primary' })`,
    ],
    relatedComponents: ['Tag', 'Tooltip'],
  },
  {
    name: 'Tag',
    category: 'atoms',
    description: 'Labeled tag with optional remove button for tagging/filtering.',
    props: [
      { name: 'label', type: "string", required: true, description: 'Tag label text' },
      { name: 'color', type: "ColorValue", required: false, default: "'mutedForeground'", description: 'Tag color' },
      { name: 'removable', type: "boolean", required: false, default: 'false', description: 'Show remove button' },
      { name: 'onRemove', type: "() => void", required: false, description: 'Remove callback' },
    ],
    examples: [
      `Tag({ label: 'TypeScript', color: 'accent' })`,
      `// Removable tags\nEach(tags, (tag) =>\n  Tag({\n    label: tag,\n    removable: true,\n    onRemove: () => removeTag(tag),\n  })\n)`,
    ],
    relatedComponents: ['Badge', 'TagInput'],
  },
  {
    name: 'Tooltip',
    category: 'atoms',
    description: 'Tooltip with arrow pointing to content. Supports all positions.',
    props: [
      { name: 'content', type: "string | VNode", required: true, description: 'Tooltip content' },
      { name: 'position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'top'", description: 'Position relative to target' },
      { name: 'arrow', type: "boolean", required: false, default: 'true', description: 'Show arrow pointer' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'round'", description: 'Border style' },
      { name: 'borderColor', type: "ColorValue", required: false, default: "'border'", description: 'Border color' },
      { name: 'color', type: "ColorValue", required: false, default: "'foreground'", description: 'Text color' },
      { name: 'backgroundColor', type: "ColorValue", required: false, description: 'Background color' },
      { name: 'visible', type: "boolean", required: false, default: 'true', description: 'Visibility state' },
      { name: 'maxWidth', type: "number", required: false, description: 'Maximum width' },
    ],
    examples: [
      `Tooltip({ content: 'Press Enter to confirm', position: 'bottom' })`,
      `// Rich tooltip\nTooltip({\n  content: VStack({},\n    Text({ bold: true }, 'Shortcuts'),\n    Text({}, 'Ctrl+S: Save'),\n  ),\n  position: 'right',\n})`,
    ],
    relatedComponents: ['WithTooltip', 'HelpTooltip', 'Popover'],
  },
  {
    name: 'WithTooltip',
    category: 'atoms',
    description: 'Wrapper that shows tooltip when element is active/focused.',
    props: [
      { name: 'children', type: "VNode", required: true, description: 'Target element' },
      { name: 'tooltip', type: "string | VNode", required: true, description: 'Tooltip content' },
      { name: 'position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'top'", description: 'Tooltip position' },
      { name: 'active', type: "boolean", required: false, default: 'false', description: 'Show tooltip when true' },
      { name: 'tooltipProps', type: "Partial<TooltipOptions>", required: false, description: 'Additional tooltip props' },
    ],
    examples: [
      `WithTooltip({\n  children: Button({ label: 'Submit' }),\n  tooltip: 'Press Enter to submit the form',\n  position: 'top',\n  active: isFocused,\n})`,
    ],
    relatedComponents: ['Tooltip', 'HelpTooltip'],
  },
  {
    name: 'HelpTooltip',
    category: 'atoms',
    description: 'Help icon [?] that shows tooltip when active.',
    props: [
      { name: 'text', type: "string", required: true, description: 'Help text' },
      { name: 'position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'right'", description: 'Tooltip position' },
      { name: 'active', type: "boolean", required: false, default: 'false', description: 'Show tooltip when true' },
      { name: 'icon', type: "string", required: false, default: "'?'", description: 'Help icon character' },
      { name: 'iconColor', type: "ColorValue", required: false, default: "'primary'", description: 'Icon color' },
    ],
    examples: [
      `// Next to form field\nBox({ flexDirection: 'row', gap: 1 },\n  Text({}, 'Email:'),\n  HelpTooltip({\n    text: 'Enter your email address',\n    active: emailFocused,\n  }),\n)`,
    ],
    relatedComponents: ['Tooltip', 'WithTooltip', 'InfoBox'],
  },
  {
    name: 'InfoBox',
    category: 'atoms',
    description: 'Information callout box for tips, warnings, and errors.',
    props: [
      { name: 'message', type: "string | VNode", required: true, description: 'Message content' },
      { name: 'type', type: "'info' | 'warning' | 'error' | 'success' | 'tip'", required: false, default: "'info'", description: 'Box type (affects colors and icon)' },
      { name: 'title', type: "string", required: false, description: 'Optional title' },
      { name: 'showIcon', type: "boolean", required: false, default: 'true', description: 'Show type icon' },
      { name: 'width', type: "number", required: false, description: 'Fixed width' },
    ],
    examples: [
      `InfoBox({ type: 'warning', title: 'Caution', message: 'This action cannot be undone.' })`,
      `InfoBox({ type: 'tip', message: 'Press Tab to autocomplete' })`,
      `InfoBox({ type: 'error', message: 'Connection failed. Retrying...' })`,
    ],
    relatedComponents: ['Toast', 'AlertBox'],
  },
  {
    name: 'Popover',
    category: 'atoms',
    description: 'Positioned popover content box for menus and dropdowns.',
    props: [
      { name: 'content', type: "VNode", required: true, description: 'Popover content' },
      { name: 'position', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'bottom'", description: 'Position relative to trigger' },
      { name: 'visible', type: "boolean", required: false, default: 'true', description: 'Visibility state' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'round'", description: 'Border style' },
      { name: 'borderColor', type: "ColorValue", required: false, default: "'border'", description: 'Border color' },
      { name: 'width', type: "number", required: false, description: 'Fixed width' },
      { name: 'arrow', type: "boolean", required: false, default: 'true', description: 'Show arrow' },
    ],
    examples: [
      `Popover({\n  content: VStack({},\n    Text({}, 'Option 1'),\n    Text({}, 'Option 2'),\n    Text({}, 'Option 3'),\n  ),\n  position: 'bottom',\n  visible: menuOpen(),\n  width: 20,\n})`,
    ],
    relatedComponents: ['Tooltip', 'Modal', 'CommandPalette'],
  },
  {
    name: 'BigText',
    category: 'atoms',
    description: 'Large ASCII art text with multiple font styles and gradient support.',
    props: [
      { name: 'text', type: "string", required: true, description: 'Text to display' },
      { name: 'font', type: "'block' | 'slant' | 'small' | 'standard' | 'banner' | 'mini' | 'shadow' | 'doom' | 'graffiti'", required: false, default: "'block'", description: 'Font style' },
      { name: 'color', type: "ColorValue", required: false, default: "'white'", description: 'Text color' },
      { name: 'gradient', type: "ColorValue[]", required: false, description: 'Gradient colors (per character)' },
      { name: 'align', type: "'left' | 'center' | 'right'", required: false, default: "'left'", description: 'Alignment' },
      { name: 'maxWidth', type: "number", required: false, description: 'Max width for alignment' },
      { name: 'letterSpacing', type: "number", required: false, default: '1', description: 'Spacing between letters' },
    ],
    examples: [
      `BigText({ text: 'HELLO', font: 'block', color: 'cyan' })`,
      `// Rainbow gradient\nBigText({\n  text: 'RAINBOW',\n  font: 'banner',\n  gradient: ['red', 'yellow', 'green', 'cyan', 'blue', 'magenta'],\n})`,
    ],
  },
  {
    name: 'Canvas',
    category: 'atoms',
    description: '2D drawing canvas for terminal. Supports character, braille (2x4), and block (2x2) modes.',
    props: [
      { name: 'width', type: "number", required: true, description: 'Canvas width in characters' },
      { name: 'height', type: "number", required: true, description: 'Canvas height in characters' },
      { name: 'mode', type: "'character' | 'braille' | 'block'", required: false, default: "'character'", description: 'Drawing mode (braille has 8x resolution)' },
      { name: 'foreground', type: "ColorValue", required: false, description: 'Default foreground color' },
      { name: 'background', type: "ColorValue", required: false, description: 'Background color' },
      { name: 'fillChar', type: "string", required: false, default: "'█'", description: 'Fill character' },
    ],
    examples: [
      `const canvas = createCanvas({ width: 40, height: 20, mode: 'braille' });\ncanvas.line(0, 0, 39, 19);\ncanvas.circle(20, 10, 8);\nconst output = canvas.render();`,
    ],
  },
  {
    name: 'Scrollbar',
    category: 'atoms',
    description: 'Standalone scrollbar for custom scroll implementations.',
    props: [
      { name: 'height', type: "number", required: true, description: 'Height of scrollbar area (lines)' },
      { name: 'total', type: "number", required: true, description: 'Total content height' },
      { name: 'current', type: "number", required: true, description: 'Current scroll position' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Thumb color' },
      { name: 'trackColor', type: "ColorValue", required: false, default: "'gray'", description: 'Track color' },
      { name: 'thumbChar', type: "string", required: false, description: 'Custom thumb character' },
      { name: 'trackChar', type: "string", required: false, description: 'Custom track character' },
    ],
    examples: [
      `Scrollbar({ height: 10, total: 50, current: 15 })`,
      `// Custom styled\nBox({ flexDirection: 'row' },\n  Box({ width: 40 }, ...content),\n  Scrollbar({ height: 10, total: 100, current: scrollTop() }),\n)`,
    ],
    relatedComponents: ['ScrollArea', 'ScrollList'],
  },

  // =============================================================================
  // DevX Composite Inputs
  // =============================================================================
  {
    name: 'SearchInput',
    category: 'atoms',
    description: 'Text input with search icon and clear button. Use createSearchInput() for state management.',
    props: [
      { name: 'state', type: 'SearchInputState', required: false, description: 'State from createSearchInput()' },
      { name: 'value', type: 'string', required: false, description: 'Initial value (standalone mode)' },
      { name: 'placeholder', type: 'string', required: false, default: "'Search...'", description: 'Placeholder text' },
      { name: 'onChange', type: '(value: string) => void', required: false, description: 'Change handler' },
      { name: 'onSubmit', type: '(value: string) => void', required: false, description: 'Enter key handler' },
      { name: 'onClear', type: '() => void', required: false, description: 'Clear button handler' },
      { name: 'isActive', type: 'boolean | (() => boolean)', required: false, default: 'true', description: 'Is input focused' },
      { name: 'showSearchIcon', type: 'boolean', required: false, default: 'true', description: 'Show search icon' },
      { name: 'showClearButton', type: 'boolean', required: false, default: 'true', description: 'Show clear button when value' },
      { name: 'width', type: 'number', required: false, description: 'Input width' },
      { name: 'borderStyle', type: "'none' | 'single' | 'round' | 'double'", required: false, default: "'round'", description: 'Border style' },
    ],
    examples: [
      `// With state manager\nconst search = createSearchInput({\n  onSubmit: (query) => handleSearch(query),\n  onClear: () => clearResults(),\n});\nSearchInput({ state: search })`,
      `// Standalone\nSearchInput({\n  placeholder: 'Search files...',\n  onSubmit: (query) => searchFiles(query),\n})`,
    ],
    relatedComponents: ['TextInput', 'PasswordInput'],
  },
  {
    name: 'PasswordInput',
    category: 'atoms',
    description: 'Password input with visibility toggle. Use createPasswordInput() for state management.',
    props: [
      { name: 'state', type: 'PasswordInputState', required: false, description: 'State from createPasswordInput()' },
      { name: 'value', type: 'string', required: false, description: 'Initial value (standalone mode)' },
      { name: 'placeholder', type: 'string', required: false, default: "'Password'", description: 'Placeholder text' },
      { name: 'onChange', type: '(value: string) => void', required: false, description: 'Change handler' },
      { name: 'onSubmit', type: '(value: string) => void', required: false, description: 'Enter key handler' },
      { name: 'isActive', type: 'boolean | (() => boolean)', required: false, default: 'true', description: 'Is input focused' },
      { name: 'showToggle', type: 'boolean', required: false, default: 'true', description: 'Show visibility toggle' },
      { name: 'width', type: 'number', required: false, description: 'Input width' },
      { name: 'borderStyle', type: "'none' | 'single' | 'round' | 'double'", required: false, default: "'round'", description: 'Border style' },
    ],
    examples: [
      `const password = createPasswordInput({\n  onSubmit: (value) => login(value),\n});\nPasswordInput({ state: password })`,
      `// Toggle visibility programmatically\npassword.toggleVisibility();`,
    ],
    relatedComponents: ['TextInput', 'SearchInput'],
  },
  {
    name: 'NumberInput',
    category: 'atoms',
    description: 'Numeric input with increment/decrement buttons. Supports keyboard arrows.',
    props: [
      { name: 'state', type: 'NumberInputState', required: false, description: 'State from createNumberInput()' },
      { name: 'value', type: 'number', required: false, description: 'Initial value (standalone mode)' },
      { name: 'min', type: 'number', required: false, description: 'Minimum value' },
      { name: 'max', type: 'number', required: false, description: 'Maximum value' },
      { name: 'step', type: 'number', required: false, default: '1', description: 'Increment/decrement step' },
      { name: 'onChange', type: '(value: number) => void', required: false, description: 'Change handler' },
      { name: 'isActive', type: 'boolean | (() => boolean)', required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'showButtons', type: 'boolean', required: false, default: 'true', description: 'Show +/- buttons' },
      { name: 'buttonPosition', type: "'sides' | 'right'", required: false, default: "'sides'", description: 'Button layout' },
      { name: 'width', type: 'number', required: false, default: '10', description: 'Input width' },
      { name: 'borderStyle', type: "'none' | 'single' | 'round' | 'double'", required: false, default: "'round'", description: 'Border style' },
    ],
    examples: [
      `const quantity = createNumberInput({\n  initialValue: 1,\n  min: 0,\n  max: 100,\n  step: 1,\n});\nNumberInput({ state: quantity })`,
      `// Programmatic control\nquantity.increment();\nquantity.setValue(50);`,
    ],
    relatedComponents: ['Slider', 'RangeSlider'],
  },
  {
    name: 'ConfirmButton',
    category: 'atoms',
    description: 'Two-click safety button for destructive actions. First click shows confirmation, second click executes.',
    props: [
      { name: 'state', type: 'ConfirmButtonState', required: false, description: 'State from createConfirmButton()' },
      { name: 'label', type: 'string', required: true, description: 'Button label' },
      { name: 'confirmLabel', type: 'string', required: false, default: "'Are you sure?'", description: 'Label during confirmation' },
      { name: 'variant', type: 'ButtonVariant', required: false, default: "'ghost'", description: 'Initial variant' },
      { name: 'confirmVariant', type: 'ButtonVariant', required: false, default: "'solid'", description: 'Variant during confirmation' },
      { name: 'size', type: 'ButtonSize', required: false, description: 'Button size' },
      { name: 'onConfirm', type: '() => void', required: false, description: 'Called when confirmed' },
      { name: 'onCancel', type: '() => void', required: false, description: 'Called when cancelled/timeout' },
      { name: 'timeout', type: 'number', required: false, default: '3000', description: 'Confirmation timeout (ms)' },
      { name: 'showCountdown', type: 'boolean', required: false, default: 'true', description: 'Show remaining time' },
      { name: 'disabled', type: 'boolean', required: false, default: 'false', description: 'Disable button' },
      { name: 'focused', type: 'boolean', required: false, default: 'false', description: 'Focus state' },
    ],
    examples: [
      `ConfirmButton({\n  label: 'Delete',\n  confirmLabel: 'Click again to delete',\n  onConfirm: () => deleteItem(),\n})`,
      `// With state for programmatic control\nconst btn = createConfirmButton({ onConfirm: handleDelete });\nConfirmButton({ state: btn, label: 'Delete' });\n// Cancel with Escape: btn.cancel();`,
    ],
    relatedComponents: ['Button', 'Modal'],
  },
];
