/**
 * Molecules Documentation
 * Complete documentation for all molecule-level components
 */

import type { ComponentDoc } from '../types.js';

export const molecules: ComponentDoc[] = [
  // =============================================================================
  // Collapsible Components
  // =============================================================================
  {
    name: 'Collapsible',
    category: 'molecules',
    description: 'Expandable/collapsible section with keyboard support. Space/Enter toggles, arrows expand/collapse.',
    props: [
      { name: 'title', type: "string", required: false, description: 'Section title' },
      { name: 'summary', type: "string | VNode", required: false, description: 'Summary shown when collapsed' },
      { name: 'children', type: "VNode | VNode[]", required: true, description: 'Content when expanded' },
      { name: 'initialExpanded', type: "boolean", required: false, default: 'false', description: 'Initial expanded state' },
      { name: 'collapsedIcon', type: "string", required: false, description: 'Icon when collapsed' },
      { name: 'expandedIcon', type: "string", required: false, description: 'Icon when expanded' },
      { name: 'variant', type: "'primary' | 'secondary' | 'default'", required: false, default: "'default'", description: 'Theme variant' },
      { name: 'color', type: "ColorValue", required: false, description: 'Custom header color (overrides variant)' },
      { name: 'indent', type: "number", required: false, default: '2', description: 'Content indentation' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'onToggle', type: "(expanded: boolean) => void", required: false, description: 'Toggle callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "CollapsibleState", required: false, description: 'External state from createCollapsible()' },
    ],
    examples: [
      `Collapsible({\n  title: 'Advanced Options',\n  children: Box({}, Text({}, 'Hidden content'))\n})`,
      `Collapsible({\n  title: 'Deployment',\n  summary: '3 pending changes',\n  children: DeploymentDetails()\n})`,
      `// With custom icons\nCollapsible({\n  title: 'Details',\n  collapsedIcon: '📁',\n  expandedIcon: '📂',\n  children: detailsContent\n})`,
    ],
    relatedComponents: ['Accordion', 'Details', 'ExpandableText'],
  },
  {
    name: 'Accordion',
    category: 'molecules',
    description: 'Multiple collapsible sections with keyboard navigation. Supports single or multiple open sections.',
    props: [
      { name: 'sections', type: "AccordionSection[]", required: true, description: 'Array of { key, title, content, icon?, disabled? }' },
      { name: 'initialExpanded', type: "string", required: false, description: 'Initially expanded section key' },
      { name: 'multiple', type: "boolean", required: false, default: 'false', description: 'Allow multiple sections open' },
      { name: 'gap', type: "number", required: false, default: '0', description: 'Gap between sections' },
      { name: 'variant', type: "'primary' | 'secondary' | 'default'", required: false, default: "'default'", description: 'Theme variant' },
      { name: 'colorActive', type: "ColorValue", required: false, description: 'Custom active color (overrides variant)' },
      { name: 'onChange', type: "(expanded: string[]) => void", required: false, description: 'Change callback with expanded keys' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "AccordionState", required: false, description: 'External state from createAccordion()' },
    ],
    examples: [
      `Accordion({\n  sections: [\n    { key: 'general', title: 'General', content: GeneralContent() },\n    { key: 'advanced', title: 'Advanced', content: AdvancedContent() },\n  ],\n})`,
    ],
    relatedComponents: ['Collapsible', 'Tabs'],
  },
  {
    name: 'Details',
    category: 'molecules',
    description: 'Simple expandable section like HTML <details> element.',
    props: [
      { name: 'summary', type: "string", required: true, description: 'Summary text (always visible)' },
      { name: 'children', type: "VNode | VNode[]", required: true, description: 'Content when expanded' },
      { name: 'open', type: "boolean", required: false, default: 'false', description: 'Initial open state' },
      { name: 'icon', type: "string", required: false, description: 'Custom icon' },
    ],
    examples: [
      `Details({\n  summary: 'Click to see more',\n  children: Text({}, 'Hidden details here')\n})`,
    ],
    relatedComponents: ['Collapsible', 'ExpandableText'],
  },
  {
    name: 'ExpandableText',
    category: 'molecules',
    description: 'Long text with show more/less toggle. Truncates to maxLines when collapsed.',
    props: [
      { name: 'text', type: "string", required: true, description: 'Full text content' },
      { name: 'maxLines', type: "number", required: false, default: '3', description: 'Max visible lines when collapsed' },
      { name: 'showMoreLabel', type: "string", required: false, default: "'Show more'", description: 'Expand label' },
      { name: 'showLessLabel', type: "string", required: false, default: "'Show less'", description: 'Collapse label' },
      { name: 'color', type: "ColorValue", required: false, default: "'white'", description: 'Text color' },
    ],
    examples: [
      `ExpandableText({\n  text: veryLongText,\n  maxLines: 5,\n  showMoreLabel: 'Read more...',\n})`,
    ],
    relatedComponents: ['Details', 'Collapsible'],
  },

  // =============================================================================
  // Selection Components
  // =============================================================================
  {
    name: 'Select',
    category: 'molecules',
    description: 'Dropdown selection with keyboard navigation, search, and grouping.',
    props: [
      { name: 'items', type: "SelectItem[]", required: true, description: 'Array of { value, label, description?, disabled?, group? }' },
      { name: 'multiple', type: "boolean", required: false, default: 'false', description: 'Allow multiple selections (checkbox mode)' },
      { name: 'initialValue', type: "T | T[]", required: false, description: 'Initially selected value(s)' },
      { name: 'maxVisible', type: "number", required: false, default: '10', description: 'Max visible items' },
      { name: 'searchable', type: "boolean", required: false, default: 'false', description: 'Enable fuzzy search' },
      { name: 'searchPlaceholder', type: "string", required: false, default: "'Type to search...'", description: 'Search input placeholder' },
      { name: 'cursorIndicator', type: "string", required: false, description: 'Cursor indicator character' },
      { name: 'selectedIndicator', type: "string", required: false, description: 'Selected indicator (single)' },
      { name: 'checkedIndicator', type: "string", required: false, description: 'Checked indicator (multi)' },
      { name: 'uncheckedIndicator', type: "string", required: false, description: 'Unchecked indicator (multi)' },
      { name: 'colorActive', type: "ColorValue", required: false, description: 'Focused item color' },
      { name: 'colorSelected', type: "ColorValue", required: false, description: 'Selected item color' },
      { name: 'colorDisabled', type: "ColorValue", required: false, description: 'Disabled item color' },
      { name: 'showCount', type: "boolean", required: false, default: 'true', description: 'Show item count footer' },
      { name: 'fullWidth', type: "boolean", required: false, default: 'false', description: 'Expand to fill available width' },
      { name: 'onChange', type: "(value: T | T[]) => void", required: false, description: 'Selection change handler' },
      { name: 'onSubmit', type: "(value: T | T[]) => void", required: false, description: 'Submit handler (Enter)' },
      { name: 'onCancel', type: "() => void", required: false, description: 'Cancel handler (Escape)' },
      { name: 'isActive', type: "boolean | (() => boolean)", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "ReturnType<typeof createSelect>", required: false, description: 'External state from createSelect()' },
    ],
    examples: [
      `const countries = [\n  { value: 'us', label: 'United States' },\n  { value: 'uk', label: 'United Kingdom' },\n];\nconst country = useSelectState({ items: countries, searchable: true });\n\nSelect({\n  state: country,\n  items: countries,\n  onChange: (value) => setCountry(value),\n})`,
      `// Advanced explicit-state usage\nconst select = createSelect({ items: countries });\nrenderSelect(select, { items: countries, borderStyle: 'round' })`,
    ],
    relatedComponents: ['MultiSelect', 'RadioGroup', 'Combobox'],
  },
  {
    name: 'Confirm',
    category: 'molecules',
    description: 'Yes/No confirmation prompt. Quick way to get boolean confirmation.',
    props: [
      { name: 'message', type: "string", required: true, description: 'Confirmation message' },
      { name: 'yesLabel', type: "string", required: false, default: "'Yes'", description: 'Yes button label' },
      { name: 'noLabel', type: "string", required: false, default: "'No'", description: 'No button label' },
      { name: 'defaultValue', type: "boolean", required: false, default: 'false', description: 'Default selection' },
      { name: 'onConfirm', type: "(result: boolean) => void", required: false, description: 'Confirmation callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
    ],
    examples: [
      `Confirm({\n  message: 'Delete this file?',\n  onConfirm: (yes) => yes && deleteFile(),\n})`,
      `// Custom labels\nConfirm({\n  message: 'Save changes?',\n  yesLabel: 'Save',\n  noLabel: 'Discard',\n  onConfirm: handleSave,\n})`,
    ],
    relatedComponents: ['Select', 'Modal'],
  },
  {
    name: 'Checkbox',
    category: 'molecules',
    description: 'Multi-choice checkbox list. Wrapper around Select with multiple selection enabled.',
    props: [
      { name: 'items', type: "SelectItem[]", required: true, description: 'Array of { value, label, description?, disabled?, group? }' },
      { name: 'initialValue', type: "T | T[]", required: false, description: 'Initially selected value(s)' },
      { name: 'maxVisible', type: "number", required: false, default: '10', description: 'Max visible items' },
      { name: 'searchable', type: "boolean", required: false, default: 'false', description: 'Enable fuzzy search' },
      { name: 'searchPlaceholder', type: "string", required: false, default: "'Type to search...'", description: 'Search input placeholder' },
      { name: 'cursorIndicator', type: "string", required: false, description: 'Cursor indicator character' },
      { name: 'checkedIndicator', type: "string", required: false, description: 'Checked indicator' },
      { name: 'uncheckedIndicator', type: "string", required: false, description: 'Unchecked indicator' },
      { name: 'colorActive', type: "ColorValue", required: false, description: 'Focused item color' },
      { name: 'colorSelected', type: "ColorValue", required: false, description: 'Selected item color' },
      { name: 'colorDisabled', type: "ColorValue", required: false, description: 'Disabled item color' },
      { name: 'showCount', type: "boolean", required: false, default: 'true', description: 'Show item count footer' },
      { name: 'fullWidth', type: "boolean", required: false, default: 'false', description: 'Expand to fill available width' },
      { name: 'onChange', type: "(value: T | T[]) => void", required: false, description: 'Selection change handler' },
      { name: 'onSubmit', type: "(value: T | T[]) => void", required: false, description: 'Submit handler (Enter)' },
      { name: 'onCancel', type: "() => void", required: false, description: 'Cancel handler (Escape)' },
      { name: 'isActive', type: "boolean | (() => boolean)", required: false, default: 'true', description: 'Enable keyboard' },
    ],
    examples: [
      `Checkbox({\n  items: [\n    { value: 'a', label: 'Option A' },\n    { value: 'b', label: 'Option B' },\n  ],\n  initialValue: ['a'],\n  onChange: setSelected,\n})`,
    ],
    relatedComponents: ['Select', 'MultiSelect', 'RadioGroup'],
  },
  {
    name: 'MultiSelect',
    category: 'molecules',
    description: 'Multi-selection with checkboxes, fuzzy search, and tags display.',
    props: [
      { name: 'items', type: "MultiSelectItem[]", required: true, description: 'Array of { value, label, description?, disabled?, group? }' },
      { name: 'initialValue', type: "T[]", required: false, default: '[]', description: 'Initially selected values' },
      { name: 'maxVisible', type: "number", required: false, default: '10', description: 'Max visible items' },
      { name: 'searchable', type: "boolean", required: false, default: 'true', description: 'Enable fuzzy search' },
      { name: 'searchPlaceholder', type: "string", required: false, description: 'Search placeholder text' },
      { name: 'showCount', type: "boolean", required: false, default: 'true', description: 'Show selected count' },
      { name: 'showTags', type: "boolean", required: false, default: 'false', description: 'Show tags for selected items' },
      { name: 'maxTags', type: "number", required: false, default: '3', description: 'Max tags before +N more' },
      { name: 'minSelections', type: "number", required: false, default: '0', description: 'Min required selections' },
      { name: 'maxSelections', type: "number", required: false, description: 'Max allowed selections' },
      { name: 'colorActive', type: "ColorValue", required: false, default: "'primary'", description: 'Focused item color' },
      { name: 'colorSelected', type: "ColorValue", required: false, default: "'success'", description: 'Selected item color' },
      { name: 'onChange', type: "(values: T[]) => void", required: false, description: 'Selection change handler' },
      { name: 'onSubmit', type: "(values: T[]) => void", required: false, description: 'Submit handler (Enter)' },
      { name: 'onCancel', type: "() => void", required: false, description: 'Cancel handler (Escape)' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "MultiSelectState", required: false, description: 'External state from createMultiSelect()' },
    ],
    examples: [
      `MultiSelect({\n  items: [\n    { value: 'react', label: 'React' },\n    { value: 'vue', label: 'Vue' },\n    { value: 'angular', label: 'Angular' },\n  ],\n  showTags: true,\n  onChange: (frameworks) => setSelected(frameworks),\n})`,
    ],
    relatedComponents: ['Select', 'TagInput'],
  },
  {
    name: 'RadioGroup',
    category: 'molecules',
    description: 'Single selection radio buttons with keyboard navigation.',
    props: [
      { name: 'options', type: "RadioOption[]", required: true, description: 'Array of { value, label, description?, disabled? }' },
      { name: 'initialValue', type: "T", required: false, description: 'Initially selected value' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'vertical'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, description: 'Gap between options' },
      { name: 'colorActive', type: "ColorValue", required: false, default: "'primary'", description: 'Focused option color' },
      { name: 'colorSelected', type: "ColorValue", required: false, default: "'success'", description: 'Selected option color' },
      { name: 'onChange', type: "(value: T) => void", required: false, description: 'Selection change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'fullWidth', type: "boolean", required: false, default: 'false', description: 'Expand to fill available width' },
      { name: 'state', type: "RadioGroupState", required: false, description: 'External state from createRadioGroup()' },
    ],
    examples: [
      `RadioGroup({\n  options: [\n    { value: 'small', label: 'Small' },\n    { value: 'medium', label: 'Medium' },\n    { value: 'large', label: 'Large' },\n  ],\n  initialValue: 'medium',\n  onChange: (size) => console.log(size),\n})`,
    ],
    relatedComponents: ['InlineRadio', 'Select', 'ToggleGroup'],
  },
  {
    name: 'InlineRadio',
    category: 'molecules',
    description: 'Compact inline radio item. Single option display for quick choices.',
    props: [
      { name: 'selected', type: "boolean", required: true, description: 'Whether this option is selected' },
      { name: 'label', type: "string", required: true, description: 'Option label' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'color', type: "ColorValue", required: false, default: "'primary'", description: 'Selected color' },
      { name: 'onClick', type: "() => void", required: false, description: 'Click handler' },
    ],
    examples: [
      `InlineRadio({\n  selected: sortOrder() === 'asc',\n  label: 'A-Z',\n  onClick: () => setSortOrder('asc'),\n})`,
    ],
    relatedComponents: ['RadioGroup'],
  },
  {
    name: 'Autocomplete',
    category: 'molecules',
    description: 'Text input with fuzzy search suggestions. Supports custom filtering, free text, and flexible dropdown positioning. For maximum flexibility, use AutocompleteInput + AutocompleteSuggestions separately.',
    props: [
      { name: 'items', type: "AutocompleteItem[]", required: true, description: 'Array of { value, label, description?, disabled? }' },
      { name: 'placeholder', type: "string", required: false, description: 'Input placeholder' },
      { name: 'maxSuggestions', type: "number", required: false, default: '5', description: 'Max suggestions shown' },
      { name: 'minChars', type: "number", required: false, default: '1', description: 'Min chars to trigger suggestions' },
      { name: 'filter', type: "(query: string, item: AutocompleteItem) => boolean", required: false, description: 'Custom filter function' },
      { name: 'allowFreeText', type: "boolean", required: false, default: 'false', description: 'Allow non-matching input' },
      { name: 'width', type: "number", required: false, default: '30', description: 'Input width' },
      { name: 'dropdownPosition', type: "'top' | 'bottom' | 'left' | 'right'", required: false, default: "'bottom'", description: 'Position of suggestions dropdown' },
      { name: 'colorActive', type: "ColorValue", required: false, default: "'primary'", description: 'Active/highlight color' },
      { name: 'colorSelected', type: "ColorValue", required: false, default: "'success'", description: 'Selected item color' },
      { name: 'onChange', type: "(value: string) => void", required: false, description: 'Value change handler' },
      { name: 'onSelect', type: "(item: AutocompleteItem) => void", required: false, description: 'Item selection handler' },
      { name: 'onSubmit', type: "(value: string, item?: AutocompleteItem) => void", required: false, description: 'Submit handler (Enter)' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "AutocompleteState", required: false, description: 'External state from createAutocomplete()' },
    ],
    examples: [
      `// Basic usage\nAutocomplete({\n  items: countries,\n  placeholder: 'Search country...',\n  onSelect: (country) => setCountry(country.value),\n})`,
      `// Dropdown above input\nAutocomplete({\n  items: cities,\n  dropdownPosition: 'top',\n})`,
      `// For custom positioning, use separate components:\nconst state = createAutocomplete({ items })\nBox({ flexDirection: 'row', gap: 2 },\n  AutocompleteInput({ state }),\n  AutocompleteSuggestions({ state })\n)`,
    ],
    relatedComponents: ['AutocompleteInput', 'AutocompleteSuggestions', 'Combobox', 'TagInput', 'TextInput'],
  },
  {
    name: 'AutocompleteInput',
    category: 'molecules',
    description: 'Standalone input component for autocomplete. Use with createAutocomplete() state and AutocompleteSuggestions for flexible positioning of the suggestions dropdown anywhere in the component hierarchy.',
    props: [
      { name: 'state', type: "AutocompleteState", required: true, description: 'State from createAutocomplete()' },
      { name: 'placeholder', type: "string", required: false, description: 'Input placeholder' },
      { name: 'width', type: "number", required: false, default: '30', description: 'Input width' },
      { name: 'fullWidth', type: "boolean", required: false, default: 'false', description: 'Expand to fill available width' },
      { name: 'colorActive', type: "ColorValue", required: false, default: "'primary'", description: 'Active/highlight color' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'showBorder', type: "boolean", required: false, default: 'true', description: 'Show input border' },
    ],
    examples: [
      `// Suggestions to the right of input\nconst state = createAutocomplete({ items, onSelect })\n\nBox({ flexDirection: 'row', gap: 2 },\n  AutocompleteInput({ state, width: 20 }),\n  AutocompleteSuggestions({ state, width: 30 })\n)`,
      `// Suggestions above input\nBox({ flexDirection: 'column' },\n  AutocompleteSuggestions({ state }),\n  AutocompleteInput({ state })\n)`,
      `// In separate panels\nBox({ flexDirection: 'row' },\n  Box({ width: 30 },\n    Text({}, 'Search:'),\n    AutocompleteInput({ state })\n  ),\n  Box({ marginLeft: 2, width: 40 },\n    Text({}, 'Results:'),\n    AutocompleteSuggestions({ state, autoHide: false })\n  )\n)`,
    ],
    relatedComponents: ['AutocompleteSuggestions', 'Autocomplete', 'createAutocomplete'],
  },
  {
    name: 'AutocompleteSuggestions',
    category: 'molecules',
    description: 'Standalone suggestions dropdown for autocomplete. Use with createAutocomplete() state and AutocompleteInput for flexible positioning anywhere in the component hierarchy.',
    props: [
      { name: 'state', type: "AutocompleteState", required: true, description: 'State from createAutocomplete()' },
      { name: 'width', type: "number", required: false, default: '30', description: 'Dropdown width' },
      { name: 'fullWidth', type: "boolean", required: false, default: 'false', description: 'Expand to fill available width' },
      { name: 'colorActive', type: "ColorValue", required: false, default: "'primary'", description: 'Active item indicator color' },
      { name: 'colorSelected', type: "ColorValue", required: false, default: "'success'", description: 'Selected item color' },
      { name: 'showBorder', type: "boolean", required: false, default: 'true', description: 'Show border around dropdown' },
      { name: 'autoHide', type: "boolean", required: false, default: 'true', description: 'Hide when closed or no suggestions' },
      { name: 'maxHeight', type: "number", required: false, description: 'Max visible items (limits height)' },
    ],
    examples: [
      `// Always visible suggestions panel\nAutocompleteSuggestions({\n  state,\n  autoHide: false,  // Always show, even when empty\n  width: 40,\n})`,
      `// Compact dropdown\nAutocompleteSuggestions({\n  state,\n  maxHeight: 5,\n  showBorder: false,\n})`,
    ],
    relatedComponents: ['AutocompleteInput', 'Autocomplete', 'createAutocomplete'],
  },
  {
    name: 'Combobox',
    category: 'molecules',
    description: 'Autocomplete with dropdown visibility control. Opens on focus, closes on select.',
    props: [
      { name: 'items', type: "AutocompleteItem[]", required: true, description: 'Array of { value, label }' },
      { name: 'placeholder', type: "string", required: false, description: 'Input placeholder' },
      { name: 'width', type: "number", required: false, default: '30', description: 'Input width' },
      { name: 'maxSuggestions', type: "number", required: false, default: '5', description: 'Max suggestions shown' },
      { name: 'allowFreeText', type: "boolean", required: false, default: 'false', description: 'Allow custom values' },
      { name: 'onChange', type: "(value: string) => void", required: false, description: 'Value change handler' },
      { name: 'onSelect', type: "(item: AutocompleteItem) => void", required: false, description: 'Selection handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
    ],
    examples: [
      `Combobox({\n  items: cities,\n  placeholder: 'Select or type city...',\n  allowFreeText: true,\n  onSelect: (city) => setCity(city.value),\n})`,
    ],
    relatedComponents: ['Autocomplete', 'Select'],
  },
  {
    name: 'TagInput',
    category: 'molecules',
    description: 'Input for adding multiple tags with autocomplete suggestions.',
    props: [
      { name: 'suggestions', type: "TagItem[]", required: false, default: '[]', description: 'Autocomplete suggestions' },
      { name: 'initialTags', type: "T[]", required: false, default: '[]', description: 'Initially added tags' },
      { name: 'placeholder', type: "string", required: false, default: "'Add tag...'", description: 'Input placeholder' },
      { name: 'width', type: "number", required: false, default: '40', description: 'Component width' },
      { name: 'maxTags', type: "number", required: false, description: 'Maximum allowed tags' },
      { name: 'allowDuplicates', type: "boolean", required: false, default: 'false', description: 'Allow duplicate tags' },
      { name: 'allowCustom', type: "boolean", required: false, default: 'true', description: 'Allow custom (non-suggestion) tags' },
      { name: 'tagColor', type: "ColorValue", required: false, default: "'primary'", description: 'Tag color' },
      { name: 'onChange', type: "(tags: T[]) => void", required: false, description: 'Tags change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "TagInputState", required: false, description: 'External state from createTagInput()' },
    ],
    examples: [
      `TagInput({\n  suggestions: [\n    { value: 'react', label: 'React' },\n    { value: 'vue', label: 'Vue' },\n  ],\n  placeholder: 'Add framework...',\n  onChange: (tags) => setTags(tags),\n})`,
    ],
    relatedComponents: ['Autocomplete', 'Tag', 'MultiSelect'],
  },

  // =============================================================================
  // Composite Inputs
  // =============================================================================
  {
    name: 'SearchInput',
    category: 'molecules',
    description: 'Text input with search icon and clear button. Use createSearchInput() for state management.',
    props: [
      { name: 'state', type: 'SearchInputState', required: false, description: 'State from createSearchInput()' },
      { name: 'value', type: 'string', required: false, description: 'Initial value (standalone mode)' },
      { name: 'placeholder', type: 'string', required: false, default: "'Search...'", description: 'Placeholder text' },
      { name: 'onChange', type: '(value: string) => void', required: false, description: 'Change handler' },
      { name: 'onSubmit', type: '(value: string) => void', required: false, description: 'Enter key handler' },
      { name: 'onClear', type: '() => void', required: false, description: 'Clear button handler' },
      { name: 'isActive', type: 'boolean | (() => boolean)', required: false, default: 'true', description: 'Is input focused' },
      { name: 'showSearchIcon', type: 'boolean', required: false, default: 'true', description: 'Show search icon' },
      { name: 'showClearButton', type: 'boolean', required: false, default: 'true', description: 'Show clear button when value' },
      { name: 'width', type: 'number', required: false, description: 'Input width' },
      { name: 'borderStyle', type: "'none' | 'single' | 'round' | 'double'", required: false, default: "'round'", description: 'Border style' },
    ],
    examples: [
      `// With state manager\nconst search = createSearchInput({\n  onSubmit: (query) => handleSearch(query),\n  onClear: () => clearResults(),\n});\nSearchInput({ state: search })`,
      `// Standalone\nSearchInput({\n  placeholder: 'Search files...',\n  onSubmit: (query) => searchFiles(query),\n})`,
    ],
    relatedComponents: ['TextInput', 'PasswordInput'],
  },
  {
    name: 'PasswordInput',
    category: 'molecules',
    description: 'Password input with visibility toggle. Use createPasswordInput() for state management.',
    props: [
      { name: 'state', type: 'PasswordInputState', required: false, description: 'State from createPasswordInput()' },
      { name: 'value', type: 'string', required: false, description: 'Initial value (standalone mode)' },
      { name: 'placeholder', type: 'string', required: false, default: "'Password'", description: 'Placeholder text' },
      { name: 'onChange', type: '(value: string) => void', required: false, description: 'Change handler' },
      { name: 'onSubmit', type: '(value: string) => void', required: false, description: 'Enter key handler' },
      { name: 'isActive', type: 'boolean | (() => boolean)', required: false, default: 'true', description: 'Is input focused' },
      { name: 'showToggle', type: 'boolean', required: false, default: 'true', description: 'Show visibility toggle' },
      { name: 'width', type: 'number', required: false, description: 'Input width' },
      { name: 'borderStyle', type: "'none' | 'single' | 'round' | 'double'", required: false, default: "'round'", description: 'Border style' },
    ],
    examples: [
      `const password = createPasswordInput({\n  onSubmit: (value) => login(value),\n});\nPasswordInput({ state: password })`,
      `// Toggle visibility programmatically\npassword.toggleVisibility();`,
    ],
    relatedComponents: ['TextInput', 'SearchInput'],
  },
  {
    name: 'NumberInput',
    category: 'molecules',
    description: 'Numeric input with increment/decrement buttons. Supports keyboard arrows.',
    props: [
      { name: 'state', type: 'NumberInputState', required: false, description: 'State from createNumberInput()' },
      { name: 'value', type: 'number', required: false, description: 'Initial value (standalone mode)' },
      { name: 'min', type: 'number', required: false, description: 'Minimum value' },
      { name: 'max', type: 'number', required: false, description: 'Maximum value' },
      { name: 'step', type: 'number', required: false, default: '1', description: 'Increment/decrement step' },
      { name: 'onChange', type: '(value: number) => void', required: false, description: 'Change handler' },
      { name: 'isActive', type: 'boolean | (() => boolean)', required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'showButtons', type: 'boolean', required: false, default: 'true', description: 'Show +/- buttons' },
      { name: 'buttonPosition', type: "'sides' | 'right'", required: false, default: "'sides'", description: 'Button layout' },
      { name: 'width', type: 'number', required: false, default: '10', description: 'Input width' },
      { name: 'borderStyle', type: "'none' | 'single' | 'round' | 'double'", required: false, default: "'round'", description: 'Border style' },
    ],
    examples: [
      `const quantity = createNumberInput({\n  initialValue: 1,\n  min: 0,\n  max: 100,\n  step: 1,\n});\nNumberInput({ state: quantity })`,
      `// Programmatic control\nquantity.increment();\nquantity.setValue(50);`,
    ],
    relatedComponents: ['Slider', 'RangeSlider'],
  },
  {
    name: 'ConfirmButton',
    category: 'molecules',
    description: 'Two-click safety button for destructive actions. First click shows confirmation, second click executes.',
    props: [
      { name: 'state', type: 'ConfirmButtonState', required: false, description: 'State from createConfirmButton()' },
      { name: 'label', type: 'string', required: true, description: 'Button label' },
      { name: 'confirmLabel', type: 'string', required: false, default: "'Are you sure?'", description: 'Label during confirmation' },
      { name: 'variant', type: 'ButtonVariant', required: false, default: "'ghost'", description: 'Initial variant' },
      { name: 'confirmVariant', type: 'ButtonVariant', required: false, default: "'solid'", description: 'Variant during confirmation' },
      { name: 'size', type: 'ButtonSize', required: false, description: 'Button size' },
      { name: 'onConfirm', type: '() => void', required: false, description: 'Called when confirmed' },
      { name: 'onCancel', type: '() => void', required: false, description: 'Called when cancelled/timeout' },
      { name: 'timeout', type: 'number', required: false, default: '3000', description: 'Confirmation timeout (ms)' },
      { name: 'showCountdown', type: 'boolean', required: false, default: 'true', description: 'Show remaining time' },
      { name: 'disabled', type: 'boolean', required: false, default: 'false', description: 'Disable button' },
      { name: 'focused', type: 'boolean', required: false, default: 'false', description: 'Focus state' },
    ],
    examples: [
      `ConfirmButton({\n  label: 'Delete',\n  confirmLabel: 'Click again to delete',\n  onConfirm: () => deleteItem(),\n})`,
      `// With state for programmatic control\nconst btn = createConfirmButton({ onConfirm: handleDelete });\nConfirmButton({ state: btn, label: 'Delete' });\n// Cancel with Escape: btn.cancel();`,
    ],
    relatedComponents: ['Button', 'Modal'],
  },

  // =============================================================================
  // Table Components
  // =============================================================================
  {
    name: 'Table',
    category: 'molecules',
    description: 'Static data table with Unicode-safe sizing, headers, alignment, borders, semantic metadata, and flex columns.',
    props: [
      { name: 'columns', type: "TableColumn[]", required: true, description: 'Column definitions { key, header, width?, flex?, minWidth?, maxWidth?, align?, format?, truncate?, wrap? }' },
      { name: 'data', type: "Record<string, unknown>[]", required: true, description: 'Row data array' },
      { name: 'borderStyle', type: "'single' | 'double' | 'round' | 'bold' | 'none'", required: false, default: "'single'", description: 'Table border style' },
      { name: 'borderColor', type: "ColorValue", required: false, description: 'Border color' },
      { name: 'headerStyle', type: "{ color?, bold?, backgroundColor? }", required: false, description: 'Header styling' },
      { name: 'striped', type: "boolean", required: false, default: 'false', description: 'Alternate row styling' },
      { name: 'stripeColor', type: "ColorValue", required: false, description: 'Alternate-row color' },
      { name: 'padding', type: "number", required: false, default: '1', description: 'Horizontal cell padding' },
      { name: 'rowSeparator', type: "boolean", required: false, default: 'false', description: 'Draw separators between rows' },
      { name: 'compact', type: "boolean", required: false, default: 'false', description: 'Remove padding' },
      { name: 'maxWidth', type: "number", required: false, description: 'Maximum total table width' },
      { name: 'availableWidth', type: "number", required: false, default: 'terminal width', description: 'Available width for flex column calculation' },
      { name: 'accessibilityLabel', type: "string", required: false, default: "'Data table'", description: 'Semantic table label' },
    ],
    examples: [
      `// Basic table with fixed widths\nTable({\n  columns: [\n    { key: 'name', header: 'Name', width: 20 },\n    { key: 'age', header: 'Age', width: 5, align: 'right' },\n  ],\n  data: [\n    { name: 'Alice', age: 30 },\n    { name: 'Bob', age: 25 },\n  ],\n})`,
      `// Flex columns - fill terminal width\nTable({\n  columns: [\n    { key: 'id', header: 'ID', width: 6 },           // fixed\n    { key: 'name', header: 'Name', flex: 1 },        // 1 part\n    { key: 'desc', header: 'Description', flex: 2 }, // 2 parts\n    { key: 'status', header: 'Status', width: 10 },  // fixed\n  ],\n  data: items,\n})`,
    ],
    relatedComponents: ['SimpleTable', 'KeyValueTable', 'DataTable'],
  },
  {
    name: 'SimpleTable',
    category: 'molecules',
    description: 'Minimal table from 2D array. No configuration needed.',
    props: [
      { name: 'rows', type: "string[][]", required: true, description: '2D array of cell values' },
      { name: 'headers', type: "string[]", required: false, description: 'Optional header row' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'single'", description: 'Border style' },
    ],
    examples: [
      `SimpleTable({\n  headers: ['Name', 'Value'],\n  rows: [\n    ['CPU', '45%'],\n    ['Memory', '2.1 GB'],\n    ['Disk', '120 GB'],\n  ],\n})`,
    ],
    relatedComponents: ['Table', 'KeyValueTable'],
  },
  {
    name: 'KeyValueTable',
    category: 'molecules',
    description: 'Two-column key-value display. Perfect for details/properties.',
    props: [
      { name: 'data', type: "Record<string, string | number>", required: true, description: 'Key-value pairs object' },
      { name: 'keyWidth', type: "number", required: false, default: '15', description: 'Key column width' },
      { name: 'valueWidth', type: "number", required: false, description: 'Value column width' },
      { name: 'keyColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Key text color' },
      { name: 'separator', type: "string", required: false, default: "': '", description: 'Key-value separator' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'none'", description: 'Border style' },
    ],
    examples: [
      `KeyValueTable({\n  data: {\n    'Name': 'John Doe',\n    'Email': 'john@example.com',\n    'Role': 'Admin',\n    'Status': 'Active',\n  },\n})`,
    ],
    relatedComponents: ['Table', 'SimpleTable'],
  },

  // =============================================================================
  // Tab Components
  // =============================================================================
  {
    name: 'Tabs',
    category: 'molecules',
    description: 'Tabbed navigation with keyboard support. **API Pattern: Data-Driven** - content goes INSIDE each tab object, NOT as a children prop. Use tabs array with { key, label, content } objects.',
    props: [
      { name: 'tabs', type: "Tab[]", required: true, description: 'Array of { key, label, content, icon?, disabled? } - CONTENT GOES HERE!' },
      { name: 'initialTab', type: "T", required: false, description: 'Initially active tab key' },
      { name: 'position', type: "'top' | 'bottom'", required: false, default: "'top'", description: 'Tab bar position' },
      { name: 'style', type: "'line' | 'box' | 'pills'", required: false, default: "'line'", description: 'Tab style' },
      { name: 'variant', type: "'primary' | 'secondary' | 'default'", required: false, default: "'default'", description: 'Theme variant' },
      { name: 'colorActive', type: "ColorValue", required: false, description: 'Active tab color' },
      { name: 'colorInactive', type: "ColorValue", required: false, description: 'Inactive tab color' },
      { name: 'closable', type: "boolean", required: false, default: 'false', description: 'Allow closing tabs' },
      { name: 'showCount', type: "boolean", required: false, default: 'false', description: 'Show tab count badge' },
      { name: 'contentHeight', type: "number", required: false, description: 'Content area height' },
      { name: 'width', type: "number", required: false, description: 'Tabs width' },
      { name: 'onChange', type: "(key: T) => void", required: false, description: 'Tab change handler' },
      { name: 'onClose', type: "(key: T) => void", required: false, description: 'Tab close handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "TabsState", required: false, description: 'External state from createTabs()' },
    ],
    examples: [
      `// ✅ CORRECT - content INSIDE each tab object\nTabs({\n  tabs: [\n    { key: 'home', label: 'Home', content: HomePanel() },\n    { key: 'settings', label: 'Settings', icon: '⚙️', content: SettingsPanel() },\n  ],\n  isActive: true,\n})`,
      `// ❌ WRONG - Tabs has NO children prop\nTabs({\n  tabs: [{ key: 'a', label: 'A' }],\n  children: ContentA()  // WRONG! content goes inside tabs array\n})`,
    ],
    relatedComponents: ['TabPanel', 'VerticalTabs', 'LazyTabs'],
  },
  {
    name: 'TabPanel',
    category: 'molecules',
    description: 'Content panel for a specific tab. Renders only when tab is active.',
    props: [
      { name: 'tabs', type: "TabsState", required: true, description: 'Tabs state from createTabs()' },
      { name: 'id', type: "T", required: true, description: 'Tab id this panel belongs to' },
      { name: 'children', type: "VNode | VNode[]", required: true, description: 'Panel content' },
    ],
    examples: [
      `TabPanel({ tabs: tabsState, id: 'home' },\n  Text({}, 'Home content')\n)`,
    ],
    relatedComponents: ['Tabs'],
  },
  {
    name: 'VerticalTabs',
    category: 'molecules',
    description: 'Vertical tab layout with tabs on the left side.',
    props: [
      { name: 'tabs', type: "Tab[]", required: true, description: 'Array of { key, label, content, icon?, disabled? }' },
      { name: 'initialTab', type: "T", required: false, description: 'Initially active tab key' },
      { name: 'tabWidth', type: "number", required: false, default: '20', description: 'Tab column width' },
      { name: 'contentWidth', type: "number", required: false, description: 'Content area width' },
      { name: 'colorActive', type: "ColorValue", required: false, description: 'Active tab color' },
      { name: 'colorInactive', type: "ColorValue", required: false, description: 'Inactive tab color' },
      { name: 'onChange', type: "(key: T) => void", required: false, description: 'Tab change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "TabsState", required: false, description: 'External state from useTabsState() or createTabs()' },
    ],
    examples: [
      `VerticalTabs({\n  tabs: [\n    { key: 'general', label: '⚙️ General', content: GeneralPanel() },\n    { key: 'appearance', label: '🎨 Appearance', content: AppearancePanel() },\n    { key: 'advanced', label: '🔧 Advanced', content: AdvancedPanel() },\n  ],\n  tabWidth: 18,\n})`,
      `// Shared stable state in a wrapper\nconst tabs = useTabsState({ tabs: settingsTabs })\nVerticalTabs({ state: tabs, tabs: settingsTabs, tabWidth: 18 })`,
    ],
    relatedComponents: ['Tabs', 'LazyTabs'],
  },
  {
    name: 'LazyTabs',
    category: 'molecules',
    description: 'Tabs with lazy-loaded content. Panels only render when first activated.',
    props: [
      { name: 'tabs', type: "Tab[]", required: true, description: 'Array of { key, label, content: () => VNode }' },
      { name: 'initialTab', type: "T", required: false, description: 'Initially active tab key' },
      { name: 'position', type: "'top' | 'bottom'", required: false, default: "'top'", description: 'Tab bar position' },
      { name: 'style', type: "'line' | 'box' | 'pills'", required: false, default: "'line'", description: 'Tab style' },
      { name: 'variant', type: "'primary' | 'secondary' | 'default'", required: false, default: "'default'", description: 'Theme variant' },
      { name: 'colorActive', type: "ColorValue", required: false, description: 'Active tab color' },
      { name: 'colorInactive', type: "ColorValue", required: false, description: 'Inactive tab color' },
      { name: 'loadingContent', type: "VNode", required: false, description: 'Placeholder shown before a tab renders' },
      { name: 'onChange', type: "(key: T) => void", required: false, description: 'Tab change handler' },
      { name: 'onClose', type: "(key: T) => void", required: false, description: 'Tab close handler' },
      { name: 'closable', type: "boolean", required: false, default: 'false', description: 'Allow closing tabs' },
      { name: 'showCount', type: "boolean", required: false, default: 'false', description: 'Show tab count badge' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
    ],
    examples: [
      `LazyTabs({\n  tabs: [\n    { key: 'logs', label: 'Logs', content: () => LogsPanel() },\n    { key: 'metrics', label: 'Metrics', content: () => MetricsPanel() },\n  ],\n  loadingContent: Text({ dim: true }, 'Loading...'),\n})`,
    ],
    relatedComponents: ['Tabs', 'VerticalTabs'],
  },

  // =============================================================================
  // Tree Components
  // =============================================================================
  {
    name: 'Tree',
    category: 'molecules',
    description: 'Hierarchical tree view with keyboard navigation, expansion, and selection.',
    props: [
      { name: 'nodes', type: "TreeNode[]", required: true, description: 'Array of { id, label, icon?, children?, data?, disabled?, color? }' },
      { name: 'initialExpanded', type: "string[]", required: false, default: '[]', description: 'Initially expanded node IDs' },
      { name: 'initialSelected', type: "string[]", required: false, default: '[]', description: 'Initially selected node IDs' },
      { name: 'selectionMode', type: "'none' | 'single' | 'multiple'", required: false, default: "'single'", description: 'Selection mode' },
      { name: 'showGuides', type: "boolean", required: false, default: 'true', description: 'Show tree lines/guides' },
      { name: 'indentSize', type: "number", required: false, default: '2', description: 'Indentation size' },
      { name: 'maxDepth', type: "number", required: false, description: 'Max visible depth' },
      { name: 'colorActive', type: "ColorValue", required: false, default: "'primary'", description: 'Cursor color' },
      { name: 'colorSelected', type: "ColorValue", required: false, default: "'success'", description: 'Selected node color' },
      { name: 'colorGuide', type: "ColorValue", required: false, default: "'mutedForeground'", description: 'Guide lines color' },
      { name: 'label', type: "string", required: false, description: 'Tree title' },
      { name: 'onSelect', type: "(node: TreeNode) => void", required: false, description: 'Selection callback' },
      { name: 'onExpand', type: "(node: TreeNode) => void", required: false, description: 'Expand callback' },
      { name: 'onCollapse', type: "(node: TreeNode) => void", required: false, description: 'Collapse callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "TreeState", required: false, description: 'External state from createTree()' },
    ],
    examples: [
      `Tree({\n  nodes: [\n    {\n      id: 'src',\n      label: 'src',\n      icon: '📁',\n      children: [\n        { id: 'index.ts', label: 'index.ts', icon: '📄' },\n      ],\n    },\n  ],\n  onSelect: (node) => openFile(node.id),\n})`,
    ],
    relatedComponents: ['DirectoryTree', 'Accordion'],
  },
  {
    name: 'DirectoryTree',
    category: 'molecules',
    description: 'Data-driven directory tree with file/folder icons. For filesystem browsing, use FileBrowser.',
    props: [
      { name: 'nodes', type: "DirectoryNode[]", required: true, description: 'Directory nodes (TreeNode with { data: { type: "file" | "directory", size? } })' },
      { name: 'showSizes', type: "boolean", required: false, default: 'false', description: 'Show file sizes' },
      { name: 'showHidden', type: "boolean", required: false, default: 'false', description: 'Show hidden files (.)' },
      { name: 'colorActive', type: "ColorValue", required: false, default: "'primary'", description: 'Active item color' },
      { name: 'colorSelected', type: "ColorValue", required: false, default: "'success'", description: 'Selected item color' },
      { name: 'colorGuide', type: "ColorValue", required: false, default: "'mutedForeground'", description: 'Guide lines color' },
      { name: 'onSelect', type: "(node: DirectoryNode) => void", required: false, description: 'Selection handler' },
      { name: 'onExpand', type: "(node: DirectoryNode) => void", required: false, description: 'Expand callback' },
      { name: 'onCollapse', type: "(node: DirectoryNode) => void", required: false, description: 'Collapse callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "TreeState", required: false, description: 'External state from createTree()' },
    ],
    examples: [
      `DirectoryTree({\n  nodes: [\n    {\n      id: 'project',\n      label: 'project',\n      data: { type: 'directory' },\n      children: [\n        { id: 'src', label: 'src', data: { type: 'directory' } },\n        { id: 'package.json', label: 'package.json', data: { type: 'file', size: 1200 } },\n      ],\n    },\n  ],\n  showSizes: true,\n  onSelect: (node) => openFile(node.id),\n})`,
    ],
    relatedComponents: ['Tree', 'FileBrowser'],
  },

  // =============================================================================
  // Calendar Components
  // =============================================================================
  {
    name: 'Calendar',
    category: 'molecules',
    description: 'Interactive month calendar with date selection, events, and keyboard navigation.',
    props: [
      { name: 'initialDate', type: "Date", required: false, description: 'Initial date (defaults to today)' },
      { name: 'selectedDates', type: "Date[]", required: false, default: '[]', description: 'Initially selected dates' },
      { name: 'events', type: "CalendarEvent[]", required: false, description: 'Events to mark { date: "YYYY-MM-DD", label?, color? }' },
      { name: 'selectionMode', type: "'none' | 'single' | 'range' | 'multiple'", required: false, default: "'single'", description: 'Selection mode' },
      { name: 'firstDayOfWeek', type: "0 | 1", required: false, default: '0', description: '0=Sunday, 1=Monday' },
      { name: 'minDate', type: "Date", required: false, description: 'Minimum selectable date' },
      { name: 'maxDate', type: "Date", required: false, description: 'Maximum selectable date' },
      { name: 'disabledDates', type: "Date[]", required: false, description: 'Disabled dates' },
      { name: 'showWeekNumbers', type: "boolean", required: false, default: 'false', description: 'Show week numbers' },
      { name: 'colorToday', type: "ColorValue", required: false, default: "'success'", description: 'Today highlight color' },
      { name: 'colorSelected', type: "ColorValue", required: false, default: "'primary'", description: 'Selected date color' },
      { name: 'colorEvent', type: "ColorValue", required: false, default: "'warning'", description: 'Event marker color' },
      { name: 'colorWeekend', type: "ColorValue", required: false, default: "'mutedForeground'", description: 'Weekend color' },
      { name: 'colorHeader', type: "ColorValue", required: false, default: "'accent'", description: 'Month header color' },
      { name: 'cellWidth', type: "number", required: false, default: '4', description: 'Day cell width' },
      { name: 'onDateSelect', type: "(date: Date) => void", required: false, description: 'Selection callback' },
      { name: 'onMonthChange', type: "(year: number, month: number) => void", required: false, description: 'Month change callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "CalendarState", required: false, description: 'External state from createCalendar()' },
    ],
    examples: [
      `Calendar({\n  onDateSelect: (date) => console.log(date),\n})`,
      `// With events\nCalendar({\n  events: [\n    { date: '2024-03-15', label: 'Meeting', color: 'blue' },\n  ],\n  selectionMode: 'range',\n})`,
    ],
    relatedComponents: ['MiniCalendar', 'DatePicker'],
  },
  {
    name: 'MiniCalendar',
    category: 'molecules',
    description: 'Compact calendar for space-constrained layouts.',
    props: [
      { name: 'date', type: "Date", required: false, description: 'Displayed month/year' },
      { name: 'selectedDate', type: "Date", required: false, description: 'Selected date' },
      { name: 'cellWidth', type: "number", required: false, default: '2', description: 'Day cell width' },
      { name: 'onDateSelect', type: "(date: Date) => void", required: false, description: 'Selection handler' },
    ],
    examples: [
      `MiniCalendar({\n  selectedDate: today,\n  onDateSelect: setDate,\n})`,
    ],
    relatedComponents: ['Calendar', 'DatePicker'],
  },
  {
    name: 'DatePicker',
    category: 'molecules',
    description: 'Calendar dropdown with input field for date selection.',
    props: [
      { name: 'placeholder', type: "string", required: false, default: "'Select date...'", description: 'Input placeholder' },
      { name: 'inputWidth', type: "number", required: false, default: '20', description: 'Input field width' },
      { name: 'format', type: "string", required: false, default: "'YYYY-MM-DD'", description: 'Date display format' },
      { name: 'selectionMode', type: "'single' | 'range'", required: false, default: "'single'", description: 'Selection mode' },
      { name: 'minDate', type: "Date", required: false, description: 'Minimum date' },
      { name: 'maxDate', type: "Date", required: false, description: 'Maximum date' },
      { name: 'onDateSelect', type: "(date: Date) => void", required: false, description: 'Selection handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "DatePickerState", required: false, description: 'External state from createDatePicker()' },
    ],
    examples: [
      `DatePicker({\n  placeholder: 'Pick a date',\n  onDateSelect: (date) => setSelectedDate(date),\n})`,
    ],
    relatedComponents: ['Calendar', 'MiniCalendar'],
  },

  // =============================================================================
  // Code & Text Components
  // =============================================================================
  {
    name: 'CodeBlock',
    category: 'molecules',
    description: 'Syntax-highlighted code block with line numbers and theme support.',
    props: [
      { name: 'code', type: "string", required: true, description: 'Code content' },
      { name: 'language', type: "Language", required: false, default: "'plaintext'", description: 'Programming language (typescript, javascript, python, rust, go, etc.)' },
      { name: 'theme', type: "CodeTheme", required: false, description: 'Syntax highlighting theme' },
      { name: 'showLineNumbers', type: "boolean", required: false, default: 'true', description: 'Show line numbers' },
      { name: 'startLine', type: "number", required: false, default: '1', description: 'Starting line number' },
      { name: 'highlightLines', type: "number[]", required: false, description: 'Lines to highlight' },
      { name: 'maxWidth', type: "number", required: false, description: 'Max width (wrap long lines)' },
      { name: 'wrap', type: "boolean", required: false, default: 'false', description: 'Wrap long lines' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'round'", description: 'Border style' },
      { name: 'borderColor', type: "ColorValue", required: false, description: 'Border color' },
      { name: 'title', type: "string", required: false, description: 'Code block title/filename' },
    ],
    examples: [
      `CodeBlock({\n  code: 'const x = 1;\\nconst y = 2;',\n  language: 'typescript',\n  showLineNumbers: true,\n})`,
      `// With highlighted lines\nCodeBlock({\n  code: codeString,\n  language: 'python',\n  highlightLines: [3, 4, 5],\n  title: 'example.py',\n})`,
    ],
    relatedComponents: ['InlineCode', 'Markdown'],
  },
  {
    name: 'InlineCode',
    category: 'molecules',
    description: 'Inline code snippet with syntax highlighting. For code within text.',
    props: [
      { name: 'code', type: "string", required: true, description: 'Code content' },
      { name: 'language', type: "Language", required: false, description: 'Programming language' },
      { name: 'color', type: "ColorValue", required: false, default: "'cyan'", description: 'Code color' },
    ],
    examples: [
      `Box({ flexDirection: 'row' },\n  Text({}, 'Use '),\n  InlineCode({ code: 'useState()' }),\n  Text({}, ' for state'),\n)`,
    ],
    relatedComponents: ['CodeBlock', 'Markdown'],
  },
  {
    name: 'Markdown',
    category: 'molecules',
    description: 'Markdown renderer with support for headings, lists, code blocks, tables, and rich formatting. Automatically fills available parent width using width: 100%.',
    props: [
      { name: 'content', type: "string", required: true, description: 'Markdown content to render' },
      { name: 'maxWidth', type: "number", required: false, default: "'100%'", description: 'Max width for text wrapping. Defaults to filling parent width automatically' },
      { name: 'theme', type: "MarkdownTheme", required: false, description: 'Custom theme colors for headings, links, code, etc.' },
      { name: 'codeLineNumbers', type: "boolean", required: false, default: 'true', description: 'Show line numbers in code blocks' },
      { name: 'indentSize', type: "number", required: false, description: 'Indent size for nested elements' },
    ],
    examples: [
      `// Simple usage - auto-fills parent width\nMarkdown({ content: '# Hello\\n\\nThis is **bold** and _italic_.' })`,
      `// Inside Scroll - works automatically\nScroll(\n  { height: 20, width: 60 },\n  Markdown({ content: readme }),\n)`,
      `// With explicit maxWidth and theme\nMarkdown({\n  content: readme,\n  maxWidth: 80,\n  theme: { h1: 'cyan', link: 'blue' },\n})`,
    ],
    relatedComponents: ['CodeBlock', 'InlineCode', 'TerminalMessage', 'Scroll', 'SplitPanel'],
  },
  {
    name: 'TerminalMessage',
    category: 'molecules',
    description: 'Role-aware terminal message renderer for agent/chat output. Streams raw text, then renders completed content as Markdown with CodeBlock-backed fenced code.',
    props: [
      { name: 'content', type: "string", required: true, description: 'Message content' },
      { name: 'role', type: "'user' | 'assistant' | 'system' | 'tool'", required: false, default: "'assistant'", description: 'Message role' },
      { name: 'streaming', type: "boolean", required: false, default: 'false', description: 'Render raw text while content is streaming' },
      { name: 'showRole', type: "boolean", required: false, default: 'true', description: 'Show role header and gutter' },
      { name: 'label', type: "string", required: false, description: 'Override role label' },
      { name: 'marker', type: "string", required: false, description: 'Override role marker' },
      { name: 'color', type: "ColorValue", required: false, description: 'Override role color' },
      { name: 'roleStyles', type: "Partial<Record<TerminalMessageRole, TerminalMessageRoleStyle>>", required: false, description: 'Per-role style overrides' },
      { name: 'rawTextColor', type: "ColorValue", required: false, description: 'Color for raw streaming text' },
      { name: 'maxWidth', type: "number", required: false, description: 'Max width for Markdown rendering' },
      { name: 'codeLineNumbers', type: "boolean", required: false, default: 'true', description: 'Show line numbers in completed code blocks' },
      { name: 'codeBlock', type: "Partial<CodeBlockOptions>", required: false, description: 'Defaults passed to fenced CodeBlock renderers' },
    ],
    examples: [
      `TerminalMessage({\n  role: 'assistant',\n  content: 'Here is the fix:\\n\\n\`\`\`ts src/app.ts\\nconst ok = true;\\n\`\`\`',\n})`,
      `TerminalMessage({\n  role: 'assistant',\n  streaming: true,\n  content: 'Thinking through the patch...\\n\`\`\`ts\\nconst',\n})`,
    ],
    relatedComponents: ['Markdown', 'CodeBlock', 'InlineCode', 'ActivityTrail'],
  },
  {
    name: 'ActivityTrail',
    category: 'molecules',
    description: 'Compact activity renderer for agent/tool/shell steps. Shows status rows, progress or duration metadata, and bounded output previews that can be expanded by id.',
    props: [
      { name: 'items', type: "ActivityTrailItem[]", required: true, description: 'Activity items with id, label, status, metadata, and optional output' },
      { name: 'expandedIds', type: "string[] | Set<string>", required: false, description: 'Item ids whose output preview should be expanded' },
      { name: 'previewLines', type: "number", required: false, default: '2', description: 'Output lines shown for collapsed items' },
      { name: 'expandedPreviewLines', type: "number", required: false, description: 'Output lines shown for expanded items' },
      { name: 'maxOutputLineLength', type: "number", required: false, description: 'Maximum output line width before truncation' },
      { name: 'showOutput', type: "boolean", required: false, default: 'true', description: 'Show output previews' },
      { name: 'showProgress', type: "boolean", required: false, default: 'true', description: 'Show progress metadata' },
      { name: 'showDuration', type: "boolean", required: false, default: 'true', description: 'Show duration metadata' },
      { name: 'showStatusLabel', type: "boolean", required: false, default: 'false', description: 'Show textual status labels after markers' },
      { name: 'emptyText', type: "string", required: false, default: "'No activity'", description: 'Compact empty state text' },
      { name: 'showEmpty', type: "boolean", required: false, default: 'true', description: 'Render empty state when no items are present' },
      { name: 'statusStyles', type: "Partial<Record<ActivityStatus, Partial<ActivityTrailStatusStyle>>>", required: false, description: 'Per-status marker, label, and color overrides' },
    ],
    examples: [
      `ActivityTrail({\n  items: [\n    { id: 'read', label: 'Read src/app.ts', status: 'success', durationMs: 28 },\n    { id: 'test', label: 'Run tests', status: 'running', progress: 0.42, output: 'collecting\\nexecuting\\nwaiting' },\n  ],\n})`,
      `ActivityTrail({\n  items,\n  expandedIds: ['test'],\n  previewLines: 1,\n  expandedPreviewLines: 12,\n})`,
    ],
    relatedComponents: ['TerminalMessage', 'StatusIndicator', 'ProgressBar', 'LogViewer'],
  },

  // =============================================================================
  // Form Components (DevX)
  // =============================================================================
  {
    name: 'FormField',
    category: 'molecules',
    description: 'Wraps any input with label and error display. Supports vertical and horizontal layouts.',
    props: [
      { name: 'label', type: 'string', required: true, description: 'Field label text' },
      { name: 'required', type: 'boolean', required: false, default: 'false', description: 'Show required asterisk' },
      { name: 'error', type: 'string', required: false, description: 'Error message to display' },
      { name: 'helperText', type: 'string', required: false, description: 'Helper text (shown when no error)' },
      { name: 'labelColor', type: 'string', required: false, description: 'Label color' },
      { name: 'errorColor', type: 'string', required: false, description: 'Error color' },
      { name: 'children', type: 'VNode | VNode[]', required: true, description: 'Input component(s)' },
      { name: 'gap', type: 'number', required: false, default: '0', description: 'Gap between elements' },
      { name: 'fullWidth', type: 'boolean', required: false, default: 'false', description: 'Full width' },
      { name: 'direction', type: "'vertical' | 'horizontal'", required: false, default: "'vertical'", description: 'Layout direction' },
      { name: 'labelWidth', type: 'number', required: false, description: 'Label width (horizontal layout)' },
    ],
    examples: [
      `FormField({\n  label: 'Email',\n  required: true,\n  error: emailError(),\n  children: TextInput({ state: emailInput }),\n})`,
      `// Horizontal layout\nFormField({\n  label: 'Name',\n  direction: 'horizontal',\n  labelWidth: 15,\n  children: TextInput({ state: nameInput }),\n})`,
    ],
    relatedComponents: ['FormGroup', 'TextInput'],
  },
  {
    name: 'FormGroup',
    category: 'molecules',
    description: 'Groups multiple form fields together with optional title and description.',
    props: [
      { name: 'title', type: 'string', required: false, description: 'Group title' },
      { name: 'description', type: 'string', required: false, description: 'Group description' },
      { name: 'children', type: 'VNode | VNode[]', required: true, description: 'Form fields' },
      { name: 'gap', type: 'number', required: false, default: '1', description: 'Gap between fields' },
      { name: 'borderStyle', type: "'none' | 'single' | 'round' | 'double'", required: false, default: "'none'", description: 'Border style' },
      { name: 'padding', type: 'number', required: false, default: '0', description: 'Padding' },
    ],
    examples: [
      `FormGroup({\n  title: 'Account Settings',\n  description: 'Update your account information',\n  gap: 1,\n  children: [\n    FormField({ label: 'Name', children: TextInput({ ... }) }),\n    FormField({ label: 'Email', children: TextInput({ ... }) }),\n  ],\n})`,
    ],
    relatedComponents: ['FormField'],
  },
  {
    name: 'SplitView',
    category: 'molecules',
    description: 'Master-detail layout with built-in selection state and keyboard navigation.',
    props: [
      { name: 'state', type: 'SplitViewState<T>', required: false, description: 'State from createSplitView()' },
      { name: 'items', type: 'MaybeReactive<T[]>', required: false, description: 'Items array for uncontrolled mode' },
      { name: 'selectedIndex', type: 'MaybeReactive<number | null>', required: false, description: 'Controlled selected index' },
      { name: 'onSelect', type: '(item: T, index: number) => void', required: false, description: 'Selection callback for uncontrolled mode' },
      { name: 'renderItem', type: '(item: T, index: number, selected: boolean) => VNode', required: true, description: 'List item renderer' },
      { name: 'renderDetail', type: '(item: T | null) => VNode', required: true, description: 'Detail panel renderer' },
      { name: 'ratio', type: 'number', required: false, default: '0.33', description: 'List/detail split ratio' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'horizontal'", description: 'Layout direction' },
      { name: 'divider', type: 'boolean', required: false, default: 'true', description: 'Show divider between panels' },
      { name: 'listWidth', type: 'number', required: false, description: 'Fixed list width instead of ratio' },
      { name: 'gap', type: 'number', required: false, default: '0', description: 'Gap between panes' },
    ],
    examples: [
      `const view = createSplitView({ items: requests, initialIndex: 0 })\n\nSplitView({\n  state: view,\n  renderItem: (item, _index, selected) =>\n    ListItem({ primary: item.name, secondary: item.status, selected }),\n  renderDetail: (item) => item ? RequestDetail({ request: item }) : Text({}, 'Select a request'),\n})`,
      `// Uncontrolled mode\nSplitView({\n  items: files,\n  ratio: 0.4,\n  renderItem: (file, _index, selected) => ListItem({ primary: file.name, selected }),\n  renderDetail: (file) => file ? FilePreview({ file }) : Text({}, 'No file selected'),\n})`,
    ],
    relatedComponents: ['ListItem', 'DataRow', 'Tree'],
  },
];
