/**
 * Molecules Documentation
 */

import type { ComponentDoc } from '../types.js';

export const molecules: ComponentDoc[] = [
  {
    name: 'Collapsible',
    category: 'molecules',
    description: 'Expandable/collapsible section with keyboard support. Space/Enter toggles, arrows expand/collapse.',
    props: [
      { name: 'title', type: "string", required: true, description: 'Section title' },
      { name: 'children', type: "VNode | VNode[]", required: true, description: 'Content when expanded' },
      { name: 'initialExpanded', type: "boolean", required: false, default: 'false', description: 'Initial expanded state' },
      { name: 'collapsedIcon', type: "string", required: false, description: 'Icon when collapsed' },
      { name: 'expandedIcon', type: "string", required: false, description: 'Icon when expanded' },
      { name: 'titleColor', type: "ColorValue", required: false, default: "'white'", description: 'Title color' },
      { name: 'indent', type: "number", required: false, default: '2', description: 'Content indentation' },
      { name: 'disabled', type: "boolean", required: false, default: 'false', description: 'Disable interaction' },
      { name: 'onToggle', type: "(expanded: boolean) => void", required: false, description: 'Toggle callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "CollapsibleState", required: false, description: 'External state from createCollapsible()' },
    ],
    examples: [
      `Collapsible({\n  title: 'Advanced Options',\n  children: Box({}, Text({}, 'Hidden content'))\n})`,
      `// With custom icons\nCollapsible({\n  title: 'Details',\n  collapsedIcon: '📁',\n  expandedIcon: '📂',\n  children: detailsContent\n})`,
      `// With external control\nconst state = createCollapsible({ initialExpanded: true });\nstate.toggle(); // programmatic control\n\nCollapsible({ state, title: 'Controlled', children: content })`,
    ],
  },
  {
    name: 'Accordion',
    category: 'molecules',
    description: 'Multiple collapsible sections with keyboard navigation. Supports single or multiple open sections.',
    props: [
      { name: 'sections', type: "AccordionSection[]", required: true, description: 'Array of { key, title, content, icon?, disabled? }' },
      { name: 'initialExpanded', type: "string", required: false, description: 'Initially expanded section key' },
      { name: 'multiple', type: "boolean", required: false, default: 'false', description: 'Allow multiple sections open' },
      { name: 'gap', type: "number", required: false, default: '0', description: 'Gap between sections' },
      { name: 'titleColor', type: "ColorValue", required: false, default: "'white'", description: 'Section title color' },
      { name: 'activeColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Focused section color' },
      { name: 'onChange', type: "(expanded: string[]) => void", required: false, description: 'Change callback with expanded keys' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard handling' },
      { name: 'state', type: "AccordionState", required: false, description: 'External state from createAccordion()' },
    ],
    examples: [
      `Accordion({\n  sections: [\n    { key: 'general', title: 'General', content: GeneralContent() },\n    { key: 'advanced', title: 'Advanced', content: AdvancedContent() },\n  ],\n})`,
      `// With multiple open + hotkeys\nconst accordion = createAccordion({ sections, multiple: true });\n\nuseHotkeys('1', () => accordion.toggle('section-1'));\nuseHotkeys('2', () => accordion.toggle('section-2'));\nuseHotkeys('ctrl+e', () => accordion.expandAll());\n\nAccordion({ state: accordion, sections })`,
    ],
  },
  {
    name: 'Details',
    category: 'molecules',
    description: 'Simple expandable section like HTML <details> element.',
    props: [
      { name: 'summary', type: "string", required: true, description: 'Summary text (always visible)' },
      { name: 'children', type: "VNode | VNode[]", required: true, description: 'Content when expanded' },
      { name: 'open', type: "boolean", required: false, default: 'false', description: 'Initial open state' },
      { name: 'icon', type: "string", required: false, description: 'Custom icon' },
    ],
    examples: [
      `Details({\n  summary: 'Click to see more',\n  children: Text({}, 'Hidden details here')\n})`,
    ],
  },
  {
    name: 'ExpandableText',
    category: 'molecules',
    description: 'Long text with show more/less toggle. Truncates to maxLines when collapsed.',
    props: [
      { name: 'text', type: "string", required: true, description: 'Full text content' },
      { name: 'maxLines', type: "number", required: false, default: '3', description: 'Max visible lines when collapsed' },
      { name: 'showMoreLabel', type: "string", required: false, default: "'Show more'", description: 'Expand label' },
      { name: 'showLessLabel', type: "string", required: false, default: "'Show less'", description: 'Collapse label' },
      { name: 'color', type: "ColorValue", required: false, default: "'white'", description: 'Text color' },
    ],
    examples: [
      `ExpandableText({\n  text: veryLongText,\n  maxLines: 5,\n  showMoreLabel: 'Read more...',\n})`,
    ],
  },
  {
    name: 'Select',
    category: 'molecules',
    description: 'Dropdown selection with keyboard navigation.',
    props: [
      { name: 'options', type: "SelectOption[]", required: true, description: 'Array of { value, label } options' },
      { name: 'value', type: "string", required: true, description: 'Selected value' },
      { name: 'onChange', type: "(value: string) => void", required: true, description: 'Change handler' },
      { name: 'placeholder', type: "string", required: false, description: 'Placeholder text' },
      { name: 'focused', type: "boolean", required: false, default: 'false', description: 'Focus state' },
    ],
    examples: [
      `Select({\n  options: [{ value: 'a', label: 'Option A' }, { value: 'b', label: 'Option B' }],\n  value: selected(),\n  onChange: setSelected\n})`,
    ],
  },
  {
    name: 'RadioGroup',
    category: 'molecules',
    description: 'Single selection radio buttons with keyboard navigation.',
    props: [
      { name: 'options', type: "RadioOption[]", required: true, description: 'Array of { value, label, description?, disabled? }' },
      { name: 'initialValue', type: "T", required: false, description: 'Initially selected value' },
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'vertical'", description: 'Layout direction' },
      { name: 'gap', type: "number", required: false, description: 'Gap between options' },
      { name: 'activeColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Focused option color' },
      { name: 'selectedColor', type: "ColorValue", required: false, default: "'green'", description: 'Selected option color' },
      { name: 'onChange', type: "(value: T) => void", required: false, description: 'Selection change handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "RadioGroupState", required: false, description: 'External state from createRadioGroup()' },
    ],
    examples: [
      `RadioGroup({\n  options: [\n    { value: 'small', label: 'Small' },\n    { value: 'medium', label: 'Medium' },\n    { value: 'large', label: 'Large' },\n  ],\n  initialValue: 'medium',\n  onChange: (size) => console.log(size),\n})`,
      `// Horizontal layout\nRadioGroup({\n  options: themes,\n  direction: 'horizontal',\n  gap: 4,\n})`,
    ],
  },
  {
    name: 'Autocomplete',
    category: 'molecules',
    description: 'Text input with fuzzy search suggestions. Supports custom filtering and free text.',
    props: [
      { name: 'items', type: "AutocompleteItem[]", required: true, description: 'Array of { value, label, description?, disabled? }' },
      { name: 'placeholder', type: "string", required: false, description: 'Input placeholder' },
      { name: 'maxSuggestions', type: "number", required: false, default: '5', description: 'Max suggestions shown' },
      { name: 'minChars', type: "number", required: false, default: '1', description: 'Min chars to trigger suggestions' },
      { name: 'filter', type: "(query: string, item: AutocompleteItem) => boolean", required: false, description: 'Custom filter function' },
      { name: 'allowFreeText', type: "boolean", required: false, default: 'false', description: 'Allow non-matching input' },
      { name: 'width', type: "number", required: false, default: '30', description: 'Input width' },
      { name: 'activeColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Active suggestion color' },
      { name: 'onChange', type: "(value: string) => void", required: false, description: 'Value change handler' },
      { name: 'onSelect', type: "(item: AutocompleteItem) => void", required: false, description: 'Item selection handler' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "AutocompleteState", required: false, description: 'External state from createAutocomplete()' },
    ],
    examples: [
      `Autocomplete({\n  items: countries,\n  placeholder: 'Search country...',\n  onSelect: (country) => setCountry(country.value),\n})`,
      `// With free text\nAutocomplete({\n  items: suggestions,\n  allowFreeText: true,\n  onChange: (text) => setQuery(text),\n})`,
    ],
  },
  {
    name: 'MultiSelect',
    category: 'molecules',
    description: 'Multi-selection with checkboxes, fuzzy search, and tags display.',
    props: [
      { name: 'items', type: "MultiSelectItem[]", required: true, description: 'Array of { value, label, description?, disabled?, group? }' },
      { name: 'initialValue', type: "T[]", required: false, default: '[]', description: 'Initially selected values' },
      { name: 'maxVisible', type: "number", required: false, default: '10', description: 'Max visible items' },
      { name: 'searchable', type: "boolean", required: false, default: 'true', description: 'Enable fuzzy search' },
      { name: 'searchPlaceholder', type: "string", required: false, description: 'Search placeholder text' },
      { name: 'showCount', type: "boolean", required: false, default: 'true', description: 'Show selected count' },
      { name: 'showTags', type: "boolean", required: false, default: 'false', description: 'Show tags for selected items' },
      { name: 'maxTags', type: "number", required: false, default: '3', description: 'Max tags before +N more' },
      { name: 'minSelections', type: "number", required: false, default: '0', description: 'Min required selections' },
      { name: 'maxSelections', type: "number", required: false, description: 'Max allowed selections' },
      { name: 'activeColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Focused item color' },
      { name: 'selectedColor', type: "ColorValue", required: false, default: "'green'", description: 'Selected item color' },
      { name: 'onChange', type: "(values: T[]) => void", required: false, description: 'Selection change handler' },
      { name: 'onSubmit', type: "(values: T[]) => void", required: false, description: 'Submit handler (Enter)' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "MultiSelectState", required: false, description: 'External state from createMultiSelect()' },
    ],
    examples: [
      `MultiSelect({\n  items: [\n    { value: 'react', label: 'React' },\n    { value: 'vue', label: 'Vue' },\n    { value: 'angular', label: 'Angular' },\n  ],\n  showTags: true,\n  onChange: (frameworks) => setSelected(frameworks),\n})`,
      `// With limits\nMultiSelect({\n  items: features,\n  minSelections: 1,\n  maxSelections: 3,\n  searchable: true,\n})`,
    ],
  },
  {
    name: 'Table',
    category: 'molecules',
    description: 'Data table with headers and rows.',
    props: [
      { name: 'columns', type: "TableColumn[]", required: true, description: 'Column definitions { key, header, width }' },
      { name: 'data', type: "Record<string, unknown>[]", required: true, description: 'Row data' },
      { name: 'borderStyle', type: "BorderStyle", required: false, default: "'single'", description: 'Table border style' },
    ],
    examples: [
      `Table({\n  columns: [\n    { key: 'name', header: 'Name', width: 20 },\n    { key: 'age', header: 'Age', width: 5 }\n  ],\n  data: [{ name: 'Alice', age: 30 }]\n})`,
    ],
  },
  {
    name: 'Tabs',
    category: 'molecules',
    description: 'Tabbed navigation container.',
    props: [
      { name: 'tabs', type: "Tab[]", required: true, description: 'Array of { id, label, content } tabs' },
      { name: 'activeTab', type: "string", required: true, description: 'Active tab id' },
      { name: 'onChange', type: "(id: string) => void", required: true, description: 'Tab change handler' },
    ],
    examples: [
      `Tabs({\n  tabs: [\n    { id: 'home', label: 'Home', content: HomePanel },\n    { id: 'settings', label: 'Settings', content: SettingsPanel }\n  ],\n  activeTab: tab(),\n  onChange: setTab\n})`,
    ],
  },
  {
    name: 'Modal',
    category: 'molecules',
    description: 'Modal dialog overlay.',
    props: [
      { name: 'title', type: "string", required: false, description: 'Modal title' },
      { name: 'visible', type: "boolean", required: true, description: 'Visibility state' },
      { name: 'onClose', type: "() => void", required: false, description: 'Close handler' },
      { name: 'width', type: "number", required: false, default: '50', description: 'Modal width' },
      { name: 'children', type: "VNode", required: true, description: 'Modal content' },
    ],
    examples: [
      `Modal({\n  title: 'Confirm',\n  visible: showModal(),\n  onClose: () => setShowModal(false)\n}, Text({}, 'Are you sure?'))`,
    ],
  },
  {
    name: 'Tree',
    category: 'molecules',
    description: 'Hierarchical tree view with keyboard navigation, expansion, and selection.',
    props: [
      { name: 'nodes', type: "TreeNode[]", required: true, description: 'Array of { id, label, icon?, children?, data?, disabled?, color? }' },
      { name: 'initialExpanded', type: "string[]", required: false, default: '[]', description: 'Initially expanded node IDs' },
      { name: 'initialSelected', type: "string[]", required: false, default: '[]', description: 'Initially selected node IDs' },
      { name: 'selectionMode', type: "'none' | 'single' | 'multiple'", required: false, default: "'single'", description: 'Selection mode' },
      { name: 'showGuides', type: "boolean", required: false, default: 'true', description: 'Show tree lines/guides' },
      { name: 'indentSize', type: "number", required: false, default: '2', description: 'Indentation size' },
      { name: 'maxDepth', type: "number", required: false, description: 'Max visible depth' },
      { name: 'activeColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Cursor color' },
      { name: 'selectedColor', type: "ColorValue", required: false, default: "'green'", description: 'Selected node color' },
      { name: 'guideColor', type: "ColorValue", required: false, default: "'gray'", description: 'Guide lines color' },
      { name: 'label', type: "string", required: false, description: 'Tree title' },
      { name: 'onSelect', type: "(node: TreeNode) => void", required: false, description: 'Selection callback' },
      { name: 'onExpand', type: "(node: TreeNode) => void", required: false, description: 'Expand callback' },
      { name: 'onCollapse', type: "(node: TreeNode) => void", required: false, description: 'Collapse callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "TreeState", required: false, description: 'External state from createTree()' },
    ],
    examples: [
      `Tree({\n  nodes: [\n    {\n      id: 'src',\n      label: 'src',\n      icon: '📁',\n      children: [\n        { id: 'index.ts', label: 'index.ts', icon: '📄' },\n        { id: 'utils.ts', label: 'utils.ts', icon: '📄' },\n      ],\n    },\n  ],\n  showGuides: true,\n  onSelect: (node) => openFile(node.id),\n})`,
      `// With programmatic control\nconst tree = createTree({ nodes, selectionMode: 'multiple' });\ntree.expandAll();\ntree.select('my-node-id');\n\nTree({ state: tree, nodes })`,
    ],
  },
  {
    name: 'Calendar',
    category: 'molecules',
    description: 'Interactive month calendar with date selection, events, and keyboard navigation.',
    props: [
      { name: 'initialDate', type: "Date", required: false, description: 'Initial date (defaults to today)' },
      { name: 'selectedDates', type: "Date[]", required: false, default: '[]', description: 'Initially selected dates' },
      { name: 'events', type: "CalendarEvent[]", required: false, description: 'Events to mark { date: "YYYY-MM-DD", label?, color? }' },
      { name: 'selectionMode', type: "'none' | 'single' | 'range' | 'multiple'", required: false, default: "'single'", description: 'Selection mode' },
      { name: 'firstDayOfWeek', type: "0 | 1", required: false, default: '0', description: '0=Sunday, 1=Monday' },
      { name: 'minDate', type: "Date", required: false, description: 'Minimum selectable date' },
      { name: 'maxDate', type: "Date", required: false, description: 'Maximum selectable date' },
      { name: 'disabledDates', type: "Date[]", required: false, description: 'Disabled dates' },
      { name: 'showWeekNumbers', type: "boolean", required: false, default: 'false', description: 'Show week numbers' },
      { name: 'todayColor', type: "ColorValue", required: false, default: "'green'", description: 'Today highlight color' },
      { name: 'selectedColor', type: "ColorValue", required: false, default: "'cyan'", description: 'Selected date color' },
      { name: 'cellWidth', type: "number", required: false, default: '4', description: 'Day cell width' },
      { name: 'onDateSelect', type: "(date: Date) => void", required: false, description: 'Selection callback' },
      { name: 'onMonthChange', type: "(year: number, month: number) => void", required: false, description: 'Month change callback' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
      { name: 'state', type: "CalendarState", required: false, description: 'External state from createCalendar()' },
    ],
    examples: [
      `Calendar({\n  onDateSelect: (date) => console.log(date),\n})`,
      `// With events and range selection\nCalendar({\n  events: [\n    { date: '2024-03-15', label: 'Meeting', color: 'blue' },\n    { date: '2024-03-20', label: 'Deadline', color: 'red' },\n  ],\n  selectionMode: 'range',\n  showWeekNumbers: true,\n})`,
    ],
  },
  {
    name: 'DatePicker',
    category: 'molecules',
    description: 'Calendar dropdown with input field for date selection.',
    props: [
      { name: 'placeholder', type: "string", required: false, default: "'Select date...'", description: 'Input placeholder' },
      { name: 'inputWidth', type: "number", required: false, default: '20', description: 'Input field width' },
      { name: 'format', type: "string", required: false, default: "'YYYY-MM-DD'", description: 'Date display format' },
      { name: 'selectionMode', type: "'single' | 'range'", required: false, default: "'single'", description: 'Selection mode' },
      { name: 'minDate', type: "Date", required: false, description: 'Minimum date' },
      { name: 'maxDate', type: "Date", required: false, description: 'Maximum date' },
      { name: 'isActive', type: "boolean", required: false, default: 'true', description: 'Enable keyboard' },
    ],
    examples: [
      `DatePicker({\n  placeholder: 'Pick a date',\n  onDateSelect: (date) => setSelectedDate(date),\n})`,
    ],
  },
  {
    name: 'SplitPanel',
    category: 'molecules',
    description: 'Resizable split panel layout.',
    props: [
      { name: 'direction', type: "'horizontal' | 'vertical'", required: false, default: "'horizontal'", description: 'Split direction' },
      { name: 'initialSize', type: "number", required: false, default: '50', description: 'Initial size percentage' },
      { name: 'minSize', type: "number", required: false, default: '10', description: 'Minimum size percentage' },
      { name: 'left', type: "VNode", required: true, description: 'Left/top panel content' },
      { name: 'right', type: "VNode", required: true, description: 'Right/bottom panel content' },
    ],
    examples: [
      `SplitPanel({\n  direction: 'horizontal',\n  initialSize: 30,\n  left: Sidebar(),\n  right: MainContent()\n})`,
    ],
  },
  {
    name: 'Grid',
    category: 'molecules',
    description: 'CSS Grid-like layout for terminal.',
    props: [
      { name: 'columns', type: "number | string", required: true, description: 'Number of columns or template' },
      { name: 'rows', type: "number | string", required: false, description: 'Number of rows or template' },
      { name: 'gap', type: "number", required: false, default: '0', description: 'Gap between cells' },
    ],
    examples: [
      `Grid({ columns: 3, gap: 1 },\n  ...cards.map(card => Card(card))\n)`,
    ],
  },
];
