/**
 * Modal/Window Component - Pop-up dialogs for Tuiuiu
 *
 * Features:
 * - Centered modal dialogs
 * - Floating windows with position
 * - Confirmation dialogs
 * - Alert/info boxes
 * - Toast notifications
 * - Backdrop overlay
 *
 * @example
 * ```typescript
 * import { Modal, ConfirmDialog, Toast, openModal } from './modal.js';
 *
 * // Simple modal
 * When(showModal(),
 *   Modal({
 *     title: 'Settings',
 *     content: SettingsForm(),
 *     onClose: () => setShowModal(false)
 *   })
 * )
 *
 * // Confirmation dialog
 * ConfirmDialog({
 *   title: 'Delete File?',
 *   message: 'This action cannot be undone.',
 *   onConfirm: handleDelete,
 *   onCancel: closeDialog
 * })
 * ```
 */

import { Box, Text } from '../primitives/nodes.js';
import type { VNode } from '../utils/types.js';
import { getTheme, getContrastColor } from '../core/theme.js';
import { getRenderMode } from '../core/capabilities.js';
import { warnIfUnexpectedPropProvided } from '../core/dev-warnings.js';
import { createSignal } from '../primitives/signal.js';
import { stringWidth } from '../utils/text-utils.js';
import { segmentGraphemes } from '../utils/grapheme.js';
import {
  getOverlayHost,
  type OverlayCloseReason,
  type OverlayHost,
  type OverlayPriority,
  type OverlaySession,
} from '../interaction/overlay.js';

/** Icons for Toast and AlertBox - with ASCII fallbacks */
const ICONS_UNICODE = {
  success: '✓',
  error: '✗',
  warning: '⚠',
  info: 'ℹ',
};

const ICONS_ASCII = {
  success: '[OK]',
  error: '[X]',
  warning: '[!]',
  info: '[i]',
};

/** Get icons based on render mode */
function getIcons() {
  return getRenderMode() === 'ascii' ? ICONS_ASCII : ICONS_UNICODE;
}

export type BorderStyle = 'single' | 'double' | 'round' | 'heavy' | 'none';
export type ModalSize = 'small' | 'medium' | 'large' | 'fullscreen' | { width: number; height: number };
export type ModalPosition = 'center' | 'top' | 'bottom' | { x: number; y: number };

/**
 * Modal Props
 */
export interface ModalProps {
  /** Modal title */
  title?: string;
  /** Modal content */
  content: VNode;
  /** Modal size */
  size?: ModalSize;
  /** Modal position */
  position?: ModalPosition;
  /** Border style */
  borderStyle?: BorderStyle;
  /** Border color */
  borderColor?: string;
  /** Title color */
  titleColor?: string;
  /** Show backdrop (dim area behind modal) */
  backdrop?: boolean;
  /** Backdrop character */
  backdropChar?: string;
  /** Show close button hint */
  showCloseHint?: boolean;
  /** Close button hint text */
  closeHint?: string;
  /** Footer content */
  footer?: VNode;
  /** Padding inside modal */
  padding?: number;
  /** Show close button (X) in the title bar */
  showCloseButton?: boolean;
  /** Close callback - called when X button or backdrop is clicked */
  onClose?: () => void;
  /** Close when backdrop is clicked (default: true if onClose is provided) */
  closeOnBackdrop?: boolean;
}

export interface OpenModalOptions extends Omit<ModalProps, 'backdrop' | 'onClose'> {
  /** Stable session id. Generated by the host when omitted. */
  id?: string;
  /** Host override for tests, embedded renderers, or explicit runtime scopes. */
  host?: OverlayHost<VNode | null>;
  priority?: OverlayPriority;
  closeOnEscape?: boolean;
  timeoutMs?: number;
  beforeClose?: (reason: OverlayCloseReason) => boolean | Promise<boolean>;
  onClose?: () => void;
}

/**
 * Get modal dimensions based on size
 */
function getModalDimensions(
  size: ModalSize,
): { width: number | 'fill'; height: number | 'fill' } {
  if (typeof size === 'object') {
    if (
      !Number.isFinite(size.width)
      || !Number.isFinite(size.height)
      || size.width < 2
      || size.height < 2
    ) {
      throw new RangeError(
        'Custom modal size must use finite dimensions of at least 2x2',
      );
    }
    return {
      width: Math.trunc(size.width),
      height: Math.trunc(size.height),
    };
  }

  if (size === 'small') return { width: 40, height: 10 };
  if (size === 'large') return { width: 80, height: 22 };
  if (size === 'fullscreen') return { width: 'fill', height: 'fill' };
  return { width: 60, height: 16 };
}

/**
 * Modal Component
 *
 * Renders a modal dialog with customizable appearance and position.
 *
 * @example
 * ```typescript
 * Modal({
 *   title: 'Confirm Delete',
 *   content: Text({}, 'Are you sure you want to delete this file?'),
 *   size: 'small',
 *   position: 'center',
 *   borderStyle: 'round',
 *   borderColor: 'yellow',
 *   showCloseHint: true
 * })
 * ```
 */
export function Modal(props: ModalProps): VNode {
  const maybeMisusedProps = props as ModalProps & Record<string, unknown>;
  warnIfUnexpectedPropProvided(
    'Modal',
    'children',
    maybeMisusedProps.children,
    'Modal expects `content`, not `children`. Use `Modal({ title: "X", content: View() })`.',
  );

  const theme = getTheme();
  const {
    title,
    content,
    size = 'medium',
    position = 'center',
    borderStyle = 'round',
    borderColor = theme.accents.info,
    titleColor = theme.accents.info,
    backdrop = true,
    backdropChar = ' ',
    showCloseHint = true,
    closeHint = 'Press ESC to close',
    footer,
    padding = 1,
    showCloseButton = false,
    onClose,
    closeOnBackdrop = true,
  } = props;

  const { width, height } = getModalDimensions(size);
  if (!Number.isFinite(padding) || padding < 0) {
    throw new RangeError('Modal padding must be a finite non-negative number');
  }
  const safePadding = Math.trunc(padding);
  const backdropGraphemes = segmentGraphemes(backdropChar);
  if (
    backdropGraphemes.length !== 1
    || stringWidth(backdropGraphemes[0]!.segment) !== 1
  ) {
    throw new RangeError(
      'Modal backdropChar must contain exactly one single-cell grapheme',
    );
  }
  if (
    typeof position === 'object'
    && (
      !Number.isFinite(position.x)
      || !Number.isFinite(position.y)
      || position.x < 0
      || position.y < 0
    )
  ) {
    throw new RangeError(
      'Custom modal position must use finite non-negative coordinates',
    );
  }

  const panelChildren: VNode[] = [];
  if (showCloseButton && onClose) {
    panelChildren.push(
      Box(
        {
          alignSelf: 'flex-end',
          onClick: onClose,
          'aria-label': 'Close modal',
          role: 'button',
        },
        Text(
          { color: theme.accents.critical, bold: true },
          getRenderMode() === 'ascii' ? '[X]' : '×',
        ),
      ),
    );
  }
  panelChildren.push(
    Box(
      { flexDirection: 'column', flexGrow: 1, overflow: 'hidden' },
      content,
    ),
  );
  if (showCloseHint && closeHint) {
    panelChildren.push(
      Text(
        {
          color: theme.foreground.muted,
          dim: true,
          wrap: 'truncate-end',
        },
        closeHint,
      ),
    );
  }
  if (footer) panelChildren.push(footer);

  const panel = Box(
    {
      width,
      height,
      minWidth: 2,
      minHeight: 2,
      maxWidth: typeof width === 'number' ? width : undefined,
      maxHeight: typeof height === 'number' ? height : undefined,
      flexDirection: 'column',
      padding: safePadding,
      overflow: 'hidden',
      borderStyle,
      borderColor,
      borderText: title,
      borderTextColor: titleColor,
      borderTextBold: true,
      borderTextAlign: 'center',
      role: 'dialog',
      'aria-label': title,
    },
    ...panelChildren,
  );

  const customPosition = typeof position === 'object';
  const layer = Box(
    {
      position: 'absolute',
      top: customPosition ? Math.trunc(position.y) : 0,
      left: customPosition ? Math.trunc(position.x) : 0,
      width: customPosition ? width : 'fill',
      height: customPosition ? height : 'fill',
      alignItems: customPosition ? 'flex-start' : 'center',
      justifyContent: position === 'bottom'
        ? 'flex-end'
        : position === 'center'
          ? 'center'
          : 'flex-start',
    },
    panel,
  );

  const layers: VNode[] = [];
  if (backdrop) {
    layers.push(
      Box({
        position: 'absolute',
        top: 0,
        left: 0,
        width: 'fill',
        height: 'fill',
        backgroundColor: 'black',
        __fillChar: backdropGraphemes[0]!.segment,
        onClick: closeOnBackdrop && onClose ? onClose : undefined,
        'aria-label': 'Modal backdrop',
      }),
    );
  }
  layers.push(layer);

  return Box(
    {
      position: 'relative',
      width: 'fill',
      height: 'fill',
      overflow: 'hidden',
    },
    ...layers,
  );
}

/**
 * Open Modal presentation as a canonical OverlayHost session.
 * The host owns Escape, backdrop gestures, focus, timing, and idempotent close.
 */
export function openModal(options: OpenModalOptions): OverlaySession<VNode | null> {
  const {
    id,
    host = getOverlayHost<VNode | null>(),
    priority,
    closeOnEscape = true,
    timeoutMs,
    beforeClose,
    onClose,
    closeOnBackdrop = true,
    ...modalProps
  } = options;
  let session!: OverlaySession<VNode | null>;
  session = host.open({
    id,
    priority,
    blocking: true,
    captureFocus: true,
    closeOnEscape,
    closeOnBackdrop,
    backdrop: true,
    timeoutMs,
    beforeClose,
    onClose: () => { onClose?.(); },
    content: () => Modal({
      ...modalProps,
      backdrop: false,
      closeOnBackdrop: false,
      onClose: () => { void session.close(); },
    }),
  });
  return session;
}

/**
 * Confirmation Dialog Props
 */
export interface ConfirmDialogProps {
  /** Dialog title */
  title: string;
  /** Confirmation message */
  message: string;
  /** Confirm button text */
  confirmText?: string;
  /** Cancel button text */
  cancelText?: string;
  /** Confirm button color */
  confirmColor?: string;
  /** Cancel button color */
  cancelColor?: string;
  /** Selected button (0 = cancel, 1 = confirm) */
  selected?: number;
  /** Dialog type (affects colors) */
  type?: 'info' | 'warning' | 'danger';
  /** Callback when confirm button is clicked */
  onConfirm?: () => void;
  /** Callback when cancel button is clicked */
  onCancel?: () => void;
}

/**
 * Confirmation Dialog
 *
 * Pre-built modal for yes/no confirmations.
 *
 * @example
 * ```typescript
 * const dialog = createConfirmDialog({
 *   title: 'Delete File',
 *   message: 'This action cannot be undone.',
 *   type: 'danger'
 * });
 *
 * // Render
 * ConfirmDialog(dialog.props)
 *
 * // Handle input
 * useInput((_, key) => {
 *   if (key.leftArrow || key.rightArrow) dialog.toggle();
 *   if (key.return) dialog.activateSelected();
 *   if (key.escape) dialog.cancel();
 * });
 * ```
 */
export function ConfirmDialog(props: ConfirmDialogProps): VNode {
  const theme = getTheme();
  const {
    title,
    message,
    confirmText = 'Confirm',
    cancelText = 'Cancel',
    confirmColor = theme.accents.positive,
    cancelColor = theme.foreground.muted,
    selected = 0,
    type = 'info',
    onConfirm,
    onCancel,
  } = props;

  // Type-based colors
  const titleColors: Record<string, string> = {
    info: theme.accents.info,
    warning: theme.accents.warning,
    danger: theme.accents.critical,
  };

  const inactiveColor = theme.foreground.muted;

  const buttonRow = Box(
    { flexDirection: 'row', marginTop: 1 },
    // Cancel button
    Box(
      {
        borderStyle: selected === 0 ? 'round' : 'single',
        borderColor: selected === 0 ? cancelColor : inactiveColor,
        paddingX: 2,
        onClick: onCancel,
      },
      Text({ color: selected === 0 ? cancelColor : inactiveColor, bold: selected === 0 }, cancelText)
    ),
    Text({}, '  '),
    // Confirm button
    Box(
      {
        borderStyle: selected === 1 ? 'round' : 'single',
        borderColor: selected === 1 ? confirmColor : inactiveColor,
        paddingX: 2,
        onClick: onConfirm,
      },
      Text({ color: selected === 1 ? confirmColor : inactiveColor, bold: selected === 1 }, confirmText)
    )
  );

  return Modal({
    title,
    titleColor: titleColors[type],
    borderColor: titleColors[type],
    size: 'small',
    content: Box(
      { flexDirection: 'column' },
      Text({}, message),
      buttonRow
    ),
    showCloseHint: false,
  });
}

/**
 * Create interactive confirm dialog state
 */
export function createConfirmDialog(options: {
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  type?: 'info' | 'warning' | 'danger';
  onConfirm?: () => void;
  onCancel?: () => void;
}) {
  const [selected, setSelected] = createSignal(0);
  const activateSelected = () => {
    if (selected() === 1) {
      options.onConfirm?.();
    } else {
      options.onCancel?.();
    }
  };

  return {
    get props(): ConfirmDialogProps {
      return {
        title: options.title,
        message: options.message,
        confirmText: options.confirmText,
        cancelText: options.cancelText,
        type: options.type,
        selected: selected(),
        onConfirm: options.onConfirm,
        onCancel: options.onCancel,
      };
    },
    get selected() {
      return selected();
    },
    toggle: () => {
      setSelected(current => current === 0 ? 1 : 0);
    },
    selectCancel: () => {
      setSelected(0);
    },
    selectConfirm: () => {
      setSelected(1);
    },
    /** Activate whichever action is selected. */
    activateSelected,
    cancel: () => {
      options.onCancel?.();
    },
  };
}

/**
 * Toast notification type
 */
export type ToastType = 'success' | 'error' | 'warning' | 'info';

/**
 * Toast Props
 */
export interface ToastProps {
  /** Toast message */
  message: string;
  /** Toast type */
  type?: ToastType;
  /** Position on screen */
  position?: 'top' | 'bottom';
  /** Show icon */
  showIcon?: boolean;
  /** Expand to fill available width */
  fullWidth?: boolean;
}

/**
 * Toast Notification
 *
 * Simple notification message.
 *
 * @example
 * ```typescript
 * Toast({
 *   message: 'File saved successfully!',
 *   type: 'success',
 *   position: 'bottom'
 * })
 * ```
 */
export function Toast(props: ToastProps): VNode {
  const theme = getTheme();
  const { message, type = 'info', position, showIcon = true, fullWidth = false } = props;

  const icons = getIcons();

  // Use theme tokens for intelligent coloring
  const tokens = theme.components.toast[type];
  const icon = icons[type];

  const toast = Box(
    {
      flexDirection: 'row',
      borderStyle: 'round',
      borderColor: tokens.border,
      backgroundColor: tokens.bg,
      paddingX: 2,
      paddingY: 0,
      flexGrow: fullWidth ? 1 : 0,
    },
    showIcon ? Text({ color: tokens.iconFg, bold: true }, `${icon} `) : Text({}, ''),
    Box({ flexGrow: fullWidth ? 1 : 0 }, Text({ color: tokens.fg }, message))
  );

  if (!position) return toast;

  return Box(
    {
      position: 'absolute',
      left: 0,
      right: 0,
      top: position === 'top' ? 0 : undefined,
      bottom: position === 'bottom' ? 0 : undefined,
      alignItems: fullWidth ? 'stretch' : 'center',
    },
    toast,
  );
}

/**
 * Alert Box Props
 */
export interface AlertBoxProps {
  /** Alert title */
  title?: string;
  /** Alert message */
  message: string;
  /** Alert type */
  type?: 'success' | 'error' | 'warning' | 'info';
  /** Show icon */
  showIcon?: boolean;
  /** Expand to fill available width */
  fullWidth?: boolean;
}

/**
 * Alert Box
 *
 * Styled alert message box.
 *
 * @example
 * ```typescript
 * AlertBox({
 *   title: 'Warning',
 *   message: 'This operation may take a while.',
 *   type: 'warning'
 * })
 * ```
 */
export function AlertBox(props: AlertBoxProps): VNode {
  const theme = getTheme();
  const { title, message, type = 'info', showIcon = true, fullWidth = false } = props;

  const icons = getIcons();

  // Map AlertBox types to Toast tokens
  const toastType = type as ToastType;
  const tokens = theme.components.toast[toastType];
  const icon = icons[type];

  return Box(
    {
      borderStyle: 'round',
      borderColor: tokens.border,
      backgroundColor: tokens.bg,
      padding: 1,
      flexDirection: 'column',
      flexGrow: fullWidth ? 1 : 0,
    },
    title
      ? Box(
          { flexDirection: 'row', marginBottom: 1 },
          showIcon ? Text({ color: tokens.iconFg, bold: true }, `${icon} `) : Text({}, ''),
          Text({ color: tokens.iconFg, bold: true }, title)
        )
      : Box({}),
    Text({ color: tokens.fg }, message)
  );
}

// =============================================================================
// Window Component
// =============================================================================

/**
 * Window variant type
 */
export type WindowVariant = 'default' | 'primary' | 'success' | 'warning' | 'danger';

/**
 * Window Props
 */
export interface WindowProps {
  /** Window title */
  title: string;
  /** Window variant for semantic coloring */
  variant?: WindowVariant;
  /** Custom color override (uses getContrastColor for text) */
  color?: string;
  /** Window width */
  width?: number;
  /** Window height (content area) */
  height?: number;
  /** Show close button */
  showClose?: boolean;
  /** Show minimize button */
  showMinimize?: boolean;
  /** Show maximize button */
  showMaximize?: boolean;
  /** Close button callback */
  onClose?: () => void;
  /** Window content */
  children?: VNode | VNode[];
}

/**
 * Window Component
 *
 * Desktop-style window with title bar and optional buttons.
 * Supports semantic variants with intelligent theming.
 *
 * @example
 * ```typescript
 * Window({
 *   title: 'Settings',
 *   variant: 'primary',
 *   showClose: true,
 *   children: Text({}, 'Window content')
 * })
 * ```
 */
export function Window(props: WindowProps): VNode {
  const theme = getTheme();
  const {
    title,
    variant = 'default',
    color,
    width,
    height,
    showClose = true,
    showMinimize = false,
    showMaximize = false,
    onClose,
    children,
  } = props;

  // Get colors from theme tokens or custom color
  let titleBarBg: string;
  let titleBarFg: string;
  let bg: string;
  let border: string;
  let buttonFg: string;
  let closeFg: string;

  if (color) {
    // Custom color - use getContrastColor for text
    titleBarBg = color;
    titleBarFg = getContrastColor(color);
    bg = theme.background.base;
    border = color;
    buttonFg = titleBarFg;
    closeFg = titleBarFg;
  } else {
    // Use theme tokens based on variant
    const tokens = theme.components.window[variant];
    titleBarBg = tokens.titleBarBg;
    titleBarFg = tokens.titleBarFg;
    bg = tokens.bg;
    border = tokens.border;
    buttonFg = tokens.buttonFg;
    closeFg = tokens.closeFg;
  }

  // Build title bar buttons
  const buttons: VNode[] = [];
  if (showMinimize) {
    buttons.push(Text({ color: buttonFg }, ' ─ '));
  }
  if (showMaximize) {
    buttons.push(Text({ color: buttonFg }, ' □ '));
  }
  if (showClose) {
    buttons.push(
      Box(
        {
          onClick: onClose,
          role: onClose ? 'button' : undefined,
          'aria-label': onClose ? 'Close window' : undefined,
        },
        Text({ color: closeFg }, ' × '),
      ),
    );
  }

  return Box(
    {
      flexDirection: 'column',
      borderStyle: 'round',
      borderColor: border,
      width,
      backgroundColor: bg,
    },
    // Title bar
    Box(
      {
        flexDirection: 'row',
        backgroundColor: titleBarBg,
        paddingX: 1,
      },
      // Title
      Box({ flexGrow: 1 }, Text({ color: titleBarFg, bold: true }, title)),
      // Buttons
      Box({ flexDirection: 'row' }, ...buttons)
    ),
    // Content area
    Box(
      {
        flexDirection: 'column',
        padding: 1,
        height,
      },
      ...(Array.isArray(children) ? children : children ? [children] : [])
    )
  );
}

export type { VNode };
